### ISSUE TITLE
Add check in update script to copy metadata files from pre 4.0.0 directory only if they exist 

### ISSUE THREAD

**Issue by aparimeet** [pacstall/pacstall#1003]
### Describe the bug

On my new install of Rhino Linux, I encounter the following exception when running the `pacstall -U` command:
```
cp: cannot stat '/var/log/pacstall/metadata/*': No such file or directory
``` 

The code in update.sh assumes that there will always be something present in `'/var/log/pacstall/metadata/`. It does not handle the scenario where this directory could be empty.

As a result of this, the `cp` command fails and `'/var/log/pacstall/metadata/` is also not deleted. So, everytime pacstall is updated, this error is thrown.

The buggy code in question (present in update.sh):
```
# Pre 4.0.0 metadata dir changes
if [[ -d "/var/log/pacstall/metadata/" ]]; then
    sudo mkdir -p "/var/lib/pacstall/metadata/"
    sudo cp -r "/var/log/pacstall/metadata/"* "/var/lib/pacstall/metadata/" && sudo rm -rf "/var/log/pacstall/metadata/"
fi
```

Possible fix (tested this to be working!):
```
# Pre 4.0.0 metadata dir changes
if [[ -d "/var/log/pacstall/metadata/" ]]; then
    sudo mkdir -p "/var/lib/pacstall/metadata/"
    # If /var/log/pacstall/metadata/ is not empty
    if [[ ! -z "$(ls -A /var/log/pacstall/metadata/)" ]]; then
        sudo cp -r "/var/log/pacstall/metadata/"* "/var/lib/pacstall/metadata/"
    fi
    sudo rm -rf "/var/log/pacstall/metadata/"
fi

```

### To reproduce

1. Create the directory `/var/log/pacstall/metadata/` with no files in it.
2. Run `pacstall -U`.

### Expected behavior

The error, while copying the metadata files into the new directory, should not be thrown when pacstall is updated.

![image](https://github.com/pacstall/pacstall/assets/25587677/287c6653-058b-4624-b657-351aa0fbb25f)

### Screenshots

Screenshot of the error:

![image](https://github.com/pacstall/pacstall/assets/25587677/2b64a947-c15a-4c8e-adfb-aeef8d97f95d)

### OS version

Rhino Linux 24.04 (based on Ubuntu Noble Numbat (dev branch))

### Pacstall version

4.2.1 (pacstall master)

**Comment by Elsie19** [comment]
It's a harmless error that doesn't affect anything If you see it.
