### ISSUE TITLE
Just found pacstall so AUR for Ubuntu: could there be a Snap or a Deb package for clicking install?

### ISSUE THREAD

**Issue by vrement** [pacstall/pacstall#1006]
### Is your feature related to a problem? Please describe.

Nowadays many Ubuntu users don't even actually know there is a terminal where you "put programming code to" (as many normal users see it). So maybe it would be very good to have a simple package for a simple install of Pacstall? Deb or a Snap would do either way. AppImages require tinkering then again, on Ubuntu.

### A clear and concise description of what you want to happen.

Creation of a Snap or a Deb package.

### Describe alternatives you've considered

Flatpak? But also those require tinkering to set up on Ubuntu.

### Additional context

Ubuntu provides help on Snap packaging here: https://forum.snapcraft.io/c/snap-requests/21

**Comment by Elsie19** [comment]
We've discussed this in the past, and we've come to the conclusion that it is out of scope. If you're interested in helping to make this a thing, you could join our [discord server](https://discord.gg/yzrjXJV6K8) and we talk more!
