### ISSUE TITLE
pacstall is not updating package

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#1032]
### Describe the bug

pacstall not updating teams-for-linux-deb

### To reproduce

pacstall -Up

### Expected behavior

updates teams-for-linux-deb

### Screenshots

![image](https://github.com/pacstall/pacstall/assets/10415894/9db1eb26-d0d7-4a1d-85d2-3e038659a120)

### OS version

Tuxedo OS 2

### Pacstall version

4.3.2 Firebrick4

**Comment by Zahrun** [comment]
```
 aroun@aroun-tuxedo-x1  13ms  ~  pacstall -Qi teams-for-linux-deb
name: teams-for-linux
version: 1.3.23
description: Teams for Linux
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a standalone application using Electron.
date installed: Tue Dec 12 04:04:00 PM IST 2023
maintainer: Ismael Martinez <ismaelmartinez@gmail.com>
dependencies: libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libsecret-1-0
install type: explicitly installed
```

**Comment by Elsie19** [comment]
Send `/var/lib/pacstall/metadata/teams-for-linux`

**Comment by Elsie19** [comment]
I realized that you already send the file in the screenshot, and I'm not seeing `_remoterepo`, meaning that you installed this package locally somewhere, maybe during a `pacup`?

**Comment by Zahrun** [comment]
Yes that is very probable. So the use of pacup once will stop pacstall from updating the package

**Comment by Elsie19** [comment]
https://github.com/pacstall/pacstall-programs/pull/5032 is where I think the problem for you started to occur, based on the time installed in your screenshot.

**Comment by Zahrun** [comment]
Yep, that seems right
