### ISSUE TITLE
pacstall -Pup ask remove conf/cache with default Yes, when upgrading a package

### ISSUE THREAD

**Issue by Xdavius** [pacstall/pacstall#1035]
### Describe the bug

Using option -P to disable prompts.
Upgrading a pacstall ask to remove personal configuration and use yes as default when upgrading a package.

### To reproduce

1- pacstall -PUp

### Expected behavior

-P should mask the prompt to remove config and default has to be set as NO while upgrading a pkg.

### Screenshots

![Screenshot_20240201_121206](https://github.com/pacstall/pacstall/assets/66792063/540522df-02e7-4e98-aab2-4b484f5be41b)

### OS version

Debian Sid

### Pacstall version

4.3.2 Firebrick4 / master

**Comment by Elsie19** [comment]
Then make a PR that switches those values in the pacscript.

**Comment by Xdavius** [comment]
> Then make a PR that switches those values in the pacscript.

Sorry, I don't understand your reply.

So you think it's a pacscript problem but not a pacstall problem?

If it's the case, I don't know what I need to do on this pacscript.

**Comment by Elsie19** [comment]
Whoever made the pacscript added an `ask` function call meaning that whatever they chose as the default answer is being chosing with `-P`, meaning that you need to change the default answer in the pacscript to solve this.
