### ISSUE TITLE
MISSING : prerm function - Needed for DKMS packages and some others.

### ISSUE THREAD

**Issue by Xdavius** [pacstall/pacstall#1039]
### Is your feature related to a problem? Please describe.

Cannot use dkms remove for dkms packages

### A clear and concise description of what you want to happen.

I need the possibility to use pre_remove() function as it is the normal way to do

### Describe alternatives you've considered

I use this tweak in prepare() but it's bad : 

variables for DKMS remove are not setted if I use $DKMS_NAME so need to write in hard. Don't know why

```
#fix prerm script

sudo mkdir -p "${pkgdir}/DEBIAN/"
    echo "set -e

DKMS_NAME=nvidia
DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
DKMS_VERSION=545.29.06

dkms remove -m nvidia -v 545.29.06 --all || true" | sudo tee ${pkgdir}/DEBIAN/prerm
sudo chmod +x ${pkgdir}/DEBIAN/prerm
```

### Additional context

I am packaging Nvidia-driver for Debian, from the .run

I have other DKMS to package.

For the momment, keep them in tests in my own repository.

**Comment by Elsie19** [comment]
This will be added in 5.0.0.

**Comment by Xdavius** [comment]
> This will be added in 5.0.0.

Very very good news!!!!

**Comment by oklopfer** [comment]
solved in https://github.com/pacstall/pacstall/pull/1055 btw

**Comment by oklopfer** [comment]
@Xdavius this is available with `pre_remove()`, are we good to close?
