### ISSUE TITLE
Make behavior of `SRCDIR` consistent with PKGBUILDs

### ISSUE THREAD

**Issue by vigress8** [pacstall/pacstall#1040]
### Is your feature related to a problem? Please describe.

Currently during the build process, `SRCDIR` points to `/tmp/pacstall`, which is one level above where the package's source files are extracted into. This is not consistent with the PKGBUILD spec which states:
```
srcdir

This contains the directory where makepkg extracts, or copies, all source files.
All of the packaging functions defined above are run starting inside $srcdir
```

### A clear and concise description of what you want to happen.

Change `SRCDIR` to point to the specific package's build directory. And make the variable lowercase.

**Comment by oklopfer** [comment]
this is verbatim just the new pkgbase variable I introduced. I don’t see any reason to duplicate it.

**Comment by vigress8** [comment]
> this is verbatim just the new pkgbase variable I introduced. I don’t see any reason to duplicate it. read the changelog. #1038

Tons of PKGBUILDs use this variable, it's good to conform to the spec

**Comment by oklopfer** [comment]
resolved with https://github.com/pacstall/pacstall/pull/1045
