### ISSUE TITLE
Replace and provides uninstall deps.

### ISSUE THREAD

**Issue by Xdavius** [pacstall/pacstall#1061]
### Is your feature related to a problem? Please describe.

Tring to rebuild Mesa

```
provides=('libegl-mesa0' 'libgl1-mesa-dri' 'libglapi-mesa' 'libglu1-mesa' 'libglx-mesa0' 'libosmesa8' 'mesa-vulkan-drivers' 'mesa-vdpau-drivers' 'mesa-va-drivers' 'libxatracker2' 'libgbm1')

replace=('libegl-mesa0' 'libgl1-mesa-dri' 'libglapi-mesa' 'libglu1-mesa' 'libglx-mesa0' 'libosmesa8' 'mesa-vulkan-drivers' 'mesa-vdpau-drivers' 'mesa-va-drivers' 'libxatracker2' 'libgbm1')
```

### A clear and concise description of what you want to happen.

when installing, if I don't use replace, provide is not able to update existing packages.

the consequence is : KDE is realy depndent of mesa. So a big part of KDE is uninstalled and need to be reinstalled after installing new mesa version

### Describe alternatives you've considered

I have consider that virtual packages in provides should be installed before installing the built deb, avoiding the error : file already exist in xxxx package, and must upgrade existing packages to newer version

**Comment by Xdavius** [comment]
Hi.

Any idea about that ? I'm still reflecting on this

**Comment by Elsie19** [comment]
This is working as intended, try fixing your script to match the behavior you want it to[^1][^2][^3]

[^1]: https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides
[^2]: https://www.debian.org/doc/debian-policy/ch-relationships.html#conflicting-binary-packages-conflicts
[^3]: https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks
