### ISSUE TITLE
Add pkgver showing when use pacstall -S

### ISSUE THREAD

**Issue by Xdavius** [pacstall/pacstall#1065]
### Is your feature related to a problem? Please describe.

pacstall -S doesn't show the version of the package that will be installed

### A clear and concise description of what you want to happen.

```
davius@debian:~$ pacstall -S nvidia-driver-production-dkms-bundle 
nvidia-driver-production-dkms-bundle @ github:dev/vortex-repository
```

### Describe alternatives you've considered

I have considered a display like $pkgname@$pkgrepo $pkgver

Should be very usefull to install a package from specific repo using the format pacstall -I $pkgname@$pkgrepo

**Comment by Elsie19** [comment]
Not possible unless pacstall sources 400+ scripts during a single `-S`, which would be countless `curl` queries and a bunch of unsafe sourcing.

**Comment by Xdavius** [comment]
> Not possible unless pacstall sources 400+ scripts during a single `-S`, which would be countless `curl` queries and a bunch of unsafe sourcing.

Hi,

Maybe there is an other way... Using packagelist file is very simple and accessible (I can update it, so it's very easy)

I'm not sure but I was thinking on a second file on an other tool that could be able once a day, to update a new kind of package list in 2 columns.

As all package manager, the check of new package version is done locally.

I don't know how to explain better with my poor English.

But for users, I think it is important to know exactly what version you will install of a package. It may be working, even if it's 2/3 versions late.

For the moment, you have just the suprise discovering the version you have installed after installing it (or inspected the pkgbuild but we all know that is a geek thing)

It was a reflection I wanted to share. Even if it's not in previson for now, I think it's something important.

I also know that the information is accessible from the website. So I supposed that was no too difficult to integrate.

**Comment by Elsie19** [comment]
Vous pouvez vous exprimer en français si cela vous permet de mieux faire passer vos idées 🙂
