### ISSUE TITLE
incorrect pkgdir if an archive contains one subdirectory

### ISSUE THREAD

**Issue by raindev** [pacstall/pacstall#1077]
### Describe the bug

If a package archive contains a single directory, it will be picked as `pkgdir`, even though there are other files at the root of the extracted archive.

@vigress8 have identified the culprit as this line, where, if the archive contains a single directory, pacstall would cd into it, even though there package files one level above:
https://github.com/pacstall/pacstall/blob/2d722a3da58aebaa08bfd180b13d40058e22f3b3/misc/scripts/install-local.sh#L1098

### To reproduce

1. check out https://github.com/pacstall/pacstall-programs/pull/5851
2. install exercism-cli-bin 3.3.0: `pacstall -I packages/exercism-cli-bin/exercism-cli-bin.pacscript`

### Expected behavior

pkgdir remains at the root of the archive if there's anything else besides a single top-level directory in the package archive.

### Screenshots

```
[exercism-cli-bin.pacscript:package():19] - DEBUG: pwd
/tmp/pacstall/shell
[exercism-cli-bin.pacscript:package():20] - DEBUG: tree ..
..
|-- LICENSE
|-- README.md
|-- exercism
|-- exercism-3.3.0-linux-x86_64.tar.gz
`-- shell
    |-- README.md
    |-- exercism.fish
    |-- exercism_completion.bash
    `-- exercism_completion.zsh

2 directories, 8 files
```

### OS version

Ubuntu 23.10

### Pacstall version

4.3.2

**Comment by D-Brox** [comment]
This is fixed on develop, as we changed the way we deal with archive sources in the next major release. We will probably release it around the end of the month, so stay tuned :)

**Comment by raindev** [comment]
This ain't fixed.

See the same pacstall/pacstall-programs#5851, where exercism <= 3.2.0 builds but later versions still result in the below error due to an additional folder in the archive.

```
install: cannot stat './exercism': No such file or directory                                             
    [!] ERROR: Could not package exercism-cli-bin properly 
```

```shell
$ tar --list -f exercism-3.2.0-linux-x86_64.tar.gz 
LICENSE
README.md
exercism

$ tar --list -f exercism-3.4.0-linux-x86_64.tar.gz 
LICENSE
README.md
shell/README.md
shell/exercism.fish
shell/exercism_completion.bash
shell/exercism_completion.zsh
exercism
```

**Comment by raindev** [comment]
Basically `${_archive}` would point to the root of the archive (`tmp/pacstall/exercism-cli-bin~3.2.0`) or the only folder in the archive (`/tmp/pacstall/exercism-cli-bin~3.4.0/shell`), if one is present.

**Comment by raindev** [comment]
`$_archive` is corresponding to the old behavior intentionally, `$srcdir` should be used instead ([Discord](https://discord.com/channels/839818021207801878/866673569521991700/1238948515925983312)).

**Comment by D-Brox** [comment]
Just a heads up, `${_archive}` exists for a transitional period from 4.X.X to 5.X.X and will be removed in 6.X.X, but this will take a while to be released.

**Comment by raindev** [comment]
Additionally prepare, build, check, and package functions are run with `$srcdir` as the working directory and oftentimes do not require a `cd`.
