### ISSUE TITLE
Dependencies bleeding on upgrade

### ISSUE THREAD

**Issue by Elsie19** [pacstall/pacstall#1197]
### Describe the bug

I cannot reproduce it but I updated `steamtinkerlaunch-git`, `pacup`, and `rhino-pkg-git` with `-Up`, and the dependencies from `steamtinkerlaunch-git` bled into the rest of them.

### To reproduce

No.

### Expected behavior

Dependencies not bleeding.

### Screenshots

![image](https://github.com/user-attachments/assets/99a9e5d9-995c-4407-b457-739ad77c98d3)

### OS version

Ubuntu LTS

### Pacstall version

5.3.3 Keppel pacstall:develop

**Comment by oklopfer** [comment]
new container
install neofetch, no optdeps
install rhino-pkg-git
bump both down to pacstall0 in metadata
run update, and say yes to install neofetch optdeps
bleed happens
