### ISSUE TITLE
[BUG]- Error installing package

### ISSUE THREAD

**Issue by uplox** [pacstall/pacstall#1215]
### Describe the bug

Hi,
I'm trying to install awesome-git (but it happens with other packages too) and I get this error.
![Captura de pantalla 2024-08-13 a las 21 00 32](https://github.com/user-attachments/assets/ea95d50a-1ec7-4f04-a1d1-3585b0f3d71f)

### To reproduce

I created a new virtual machine using parallels (empty)
`yes Y | sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install)"`
`sudo pacstall -I awesome-git` *I also test it without  sudo 

### Expected behavior

It should install awesome-git without any problem.

### Screenshots

![Captura de pantalla 2024-08-13 a las 21 03 20](https://github.com/user-attachments/assets/08438658-0c7d-4bf1-9643-f5d628be7359)
![Captura de pantalla 2024-08-13 a las 21 04 25](https://github.com/user-attachments/assets/feb9b67e-3dfe-4364-b7b9-13d9a7f89f61)

### OS version

Linux 6.8.11-arm64 Kali 6.8.11-1kali2 (2024-05-30) aarch64 GNU/Linux

### Pacstall version

5.4.1 Telemagenta

**Comment by oklopfer** [comment]
Quick test suggestion:
1. edit `/etc/os-release` as root/sudo
2. change `PRETTY_NAME="Kali GNU/Linux Rolling"` to `PRETTY_NAME="Kali GNU/Linux Rolling/sid"`
3. save + close
4. try `pacstall -I awesome-git` again (it is generally advised *against* to run `pacstall` with `sudo`)
5. when done, revert the line back

If this works, then I know how to easily fix this long term.

**Comment by uplox** [comment]
The changes you suggested fix the problem. 
Thank you for your work.
