### ISSUE TITLE
Need ability to run pacstall non-interactively

### ISSUE THREAD

**Issue by ajgringo619** [pacstall/pacstall#1221]
### Is your feature related to a problem? Please describe.

I have a program that gets various VM data when I login. The issue I'm having is that `pacstall` throws a warning on non-interactive terminals, so getting the version of **Unicorn (Rhino Linux)** is a mess because of the `WARNING: Reading input from pipe` message.

### A clear and concise description of what you want to happen.

Give us a way to disable this warning, or add additional switches so that I can get specific data from a package (currently using awk).

### Describe alternatives you've considered

For now, commenting out this in `pacstall` is working:
```
#if [[ ! -t 0 ]]; then
#    NON_INTERACTIVE=true
#    fancy_message warn "Reading input from pipe"
#fi
```

### Additional context

First time using this program; a great addition to the Ubuntu world (main system is EndeavourOS, so using to having the AUR).

**Comment by Elsie19** [comment]
Have you considered redirecting stderr to `/dev/null`?

**Comment by Elsie19** [comment]
Also it would be useful to know exactly what information you're trying to retrieve.

**Comment by ajgringo619** [comment]
Didn't even consider redirecting stderr; thanks for the tip. All I'm really looking for are package versions. So far, the Unicorn Desktop is the only one I'm using that installs with pacstall.

**Comment by ajgringo619** [comment]
OK, the redirect works perfectly - thanks a bunch!

**Comment by ajgringo619** [comment]
OK, the redirect works perfectly - thanks a bunch!

**Comment by Elsie19** [comment]
> Didn't even consider redirecting stderr; thanks for the tip. All I'm really looking for are package versions. So far, the Unicorn Desktop is the only one I'm using that installs with pacstall.

For getting package versions, you can just do `pacstall -Ci $pkg version`!
