### ISSUE TITLE
option to NOT INSTALL after viewing pacscript

### ISSUE THREAD

**Issue by iconoclasthero** [pacstall/pacstall#1237]
It seems to me that one of the main points of reviewing the pacscript is to 
```
User review of pacscript;
  if necessary; then
    modify if/as necessary
  fi
  if user wishes to install; then
    proceed with processing un/modified pacscript
  else
    terminate the installation of the package.
  fi
User review of next pacscript

```

So the simplest fix would be to change the order of install and view so that one could review the pacscript before proceeding.

### Describe alternatives you've considered

I can make this change myself, but to me the logic of forcing the user to install the package after the script has been reviewed and rejected for installation is backwards.  Pacstall would be more universally useful if the order was corrected or an option to not install after reviewing the script, i.e., the user says, i've reviewed the pacscripd and **nope, I do NOT want this installed on my system**, please let me move to the next package for review and a decision on installation.

### Additional context

at the end of the day, pacstall isn't working properly and there's no way for me to easily display the pacscripts from pacstall --update, but beyond that, I don't understand why I have to agree to install it BEFORE looking at what it does and then there's the other issue [1236]? with the SIGINT handling.

**Comment by oklopfer** [comment]
@iconoclasthero this exists. use `pacstall -D foo`/`pacstall --download foo`.
