### ISSUE TITLE
Perform pacstall version check when run

### ISSUE THREAD

**Issue by iconoclasthero** [pacstall/pacstall#1238]
### Is your feature related to a problem? Please describe.

Pacstall does not inform the user that there is an update for pacstall nor does it upgrade itself in the normal course of `pacstall --upgrade`.  Many other programs for which such updates are critical let the user know that an update is available OR that do updating themselves update themselves (e.g., apt).  Coming from an Ubuntu environment, I've come to expect that this is taken care of for me simply by running the program and I'm not expected to check readmes or wikis or release notes or man pages or anything else—they just do what's needed so the end user can focus on more important things.

Again, I've come to expect this from well-designed programs; even my phone tells me when there are updates for the OS.  fdroid sent a notification yesterday that it needed to update itself...

### A clear and concise description of what you want to happen.

pacstall either updates itself automatically (apt) or inform the user that an update is available and would they like to:
1. update pacstall before continuing 
2. terminate pacstall (without requiring the sudo password) so the user can manually update pacstall before continuing.

The above are not meant to provide the end user with two options but rather one of the two, with (1) being preferred.

**Comment by Elsie19** [comment]
That is documented [here](https://github.com/pacstall/pacstall#basic-commands), [here](https://github.com/pacstall/pacstall/blob/efccbd666bfc7c88a24553e77b98476984b3ddcb/misc/man/pacstall.8#L379), and [here](https://github.com/pacstall/pacstall/wiki/FAQ#what-should-i-do-if-i-found-a-bug-in-pacstall).

**Comment by vigress8** [comment]
How is your answer at all relevant to the issue?

**Comment by Elsie19** [comment]
We provide two separate commands and I don't see a need to combine them is what I am trying to get at. There are a lot of reasons this shouldn't happen like:

- Trying to upgrade packages after running `pacstall -U .`
- Downloading pacstall every upgrade wasting bandwidth
- Pacatall is not managed by itself as a package, so it should not be treated like such

**Comment by vigress8** [comment]
A lot of programs opt for reminders to update on launch. That'd work just fine and mostly resolve this issue, since it mentions programs with this behaviour as well

**Comment by bibelin** [comment]
https://github.com/bibelin/pacstall-check-update

maybe somebody will find this useful :man_shrugging:
