### ISSUE TITLE
Arch=("i386") build AMD64 Package if amd64 is native arch, and "all" package if multiple arch are seted.

### ISSUE THREAD

**Issue by Xdavius** [pacstall/pacstall#1242]
## pacscript :

```
pkgname="lib32-libdrm"
gives="${pkgname}"
pkgdesc="Userspace interface to kernel DRM services"
pkgver="2.4.122"
pkgrel="1"
provides=("libdrm2=${pkgver}"
  "libdrm-common=${pkgver}"
  "libdrm-intel1=${pkgver}"
  "libdrm-nouveau2=${pkgver}"
  "libdrm-radeon1=${pkgver}"
  "libdrm-amdgpu1=${pkgver}"
  "libdrm-dev=${pkgver}")
replaces=("libdrm2"
  "libdrm-common"
  "libdrm-intel1"
  "libdrm-nouveau2"
  "libdrm-radeon1"
  "libdrm-amdgpu1"
  "libdrm-dev")
breaks=("${replaces[@]}")
makedepends=("python3-docutils"
  "meson"
  "ninja-build"
  "gcc-multilib"
  "g++-multilib"
  "libcairo2-dev:i386"
  "libpciaccess-dev:i386"
  "libc6-dev:i386")
arch=("i386")
url="https://dri.freedesktop.org/"
source=("https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-${pkgver}/drm-libdrm-${pkgver}.tar.gz")
sha256sums=("7babfa22795dda27f32ed78b89bf93bfd341043e254bd42734cb569b602481d3")
maintainer=("Oren Klopfer <oren@taumoda.com>" "xdavius <xdavius@github.com>")

build() {
  cd "drm-libdrm-${pkgver}"
    # Lib32
    export CC="gcc -m32"
    export CXX="g++ -m32"
    export PKG_CONFIG_PATH="/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig"
    export LIBRARY_PATH="/usr/lib/i386-linux-gnu"

  meson setup build \
    --prefix /usr \
    --libdir lib/i386-linux-gnu \
    --buildtype plain \
    --wrap-mode nofallback \
    -D udev=false \
    -D valgrind=disabled
  meson configure --no-pager build
  ninja -C build
}

package() {
  cd "drm-libdrm-${pkgver}"
  DESTDIR="${pkgdir}" ninja -C build install
  rm -fr "${pkgdir}/usr/share"
  rm -fr "${pkgdir}/usr/include"
}
```

## Generated control file : 

```
Package: lib32-libdrm
Version: 2.4.122-pacstall1
Architecture: amd64
Section: Pacstall
Priority: optional
Build-Depends: python3-docutils, meson, ninja-build, gcc-multilib, g++-multilib, libcairo2-dev:i386, libpciaccess-dev:i386, libc6-dev:i386
Provides: libdrm2 (= 2.4.122), libdrm-common (= 2.4.122), libdrm-intel1 (= 2.4.122), libdrm-nouveau2 (= 2.4.122), libdrm-radeon1 (= 2.4.122), libdrm-amdgpu1 (= 2.4.122), libdrm-dev (= 2.4.122), lib32-libdrm
Breaks: libdrm2, libdrm-common, libdrm-intel1, libdrm-nouveau2, libdrm-radeon1, libdrm-amdgpu1, libdrm-dev
Replaces: libdrm2, libdrm-common, libdrm-intel1, libdrm-nouveau2, libdrm-radeon1, libdrm-amdgpu1, libdrm-dev
Homepage: https://dri.freedesktop.org/
Maintainer: Oren Klopfer <oren@taumoda.com>
Uploaders: xdavius <xdavius@github.com>
Description: Userspace interface to kernel DRM services
Installed-Size: 501
```

Produced package : lib32-libdrm_2.4.122-pacstall1_all.deb
produced package in i386  native : lib32-libdrm_2.4.122-pacstall1_i386.deb

Produced package on amd64 native should be lib32-libdrm_2.4.122-pacstall1_amd64.deb, even if arm64 is set

### To reproduce

- Cross compil i386 package on AMD64 native architecture : results in amd64 package (should be i386)
- Compil amd64 with 2 ${arch} seted : results in all package (should be amd64)

### Expected behavior

Control file have to be : `Architecture : i386`

Packages containing more architectures should have : 
`Architecture : ${CARCH}`

if foreign build is found ${arch[0]} = ${arch[0]}
Native build have to be = ${CARCH}
crossbuild including lib32 have to be = ${CARCH}

## What is the state now ?

Now, building i386 foreign package create amd64 package so, it replace the amd64 one (in the sample, libdrm pacscript)

Building in chroot native i386 generate an i386 package. this is working.

If an all package is built, it conflicts with all foreign architectures. 

### Screenshots

![Screenshot_20240908_133646](https://github.com/user-attachments/assets/290fc792-4482-4d18-bbfc-3c79f3ca60d9)

### OS version

Debian 12

### Pacstall version

5.4.1 (master and develop)

**Comment by Xdavius** [comment]
fixes ideas : 
- Avoid crossbuild for lib32 and build foreign in chroot (For now, debootstrap doesn't work in distrobox :/ )
- Add variable crossbuild=true or chroot_build=true to set the good way to build the foreign 
- set architecture correctly (quick fix, will works for actuals lib32 arch=i386 packages) 

I hope I was clear enough...

**Comment by Xdavius** [comment]
```provides=("libdrm2=${pkgver}"
  "libdrm-common=${pkgver}"
  "libdrm-intel1=${pkgver}"
  "libdrm-nouveau2=${pkgver}"
  "libdrm-radeon1=${pkgver}"
  "libdrm-amdgpu1=${pkgver}"
  "libdrm-dev=${pkgver}")
replaces=("libdrm2"
  "libdrm-common"
  "libdrm-intel1"
  "libdrm-nouveau2"
  "libdrm-radeon1"
  "libdrm-amdgpu1"
  "libdrm-dev")
```

provides and replaces must  be declarated with ${arch[0]} for foreign build, or if chroot build, ${AARCH}

**Comment by Xdavius** [comment]
found this value in control file : 

Multi-Arch: same

right now, installing i386 (built in chroot) installed on amd64 is identified as amd64 when installed, not i386.

I think it's this value that made the installed install architecture

@oklopfer

**Comment by oklopfer** [comment]
Pacstall doesn’t support native cross-building.

When installing this pacscript, you should see a warning that pops up that says “this is for i386, which is a foreign architecture.” You have i386 support enabled, so Pacstall will allow you to build the package, but it will build it for whatever you are actually running on, not what arch variable it is.

That is because this is not the purpose of the arch variable. It is to define what architectures are supported, not what architecture is selected. It is simply checking that your machine supports the pacscript, not that the output will be a selected architecture. 

We can consider in the future adding cross-building and adding a `buildarch` variable, but that is distinguished from what `arch` is meant for.
