### ISSUE TITLE
Optional dependencies become mandatory (regression)

### ISSUE THREAD

**Issue by bibelin** [pacstall/pacstall#1254]
### Describe the bug

I created a pacscript of a program, it builds and works fine on my system with KDE Neon (based on Ubuntu 22.04). I made a PR in my fork of pacstall-programs repo (https://github.com/bibelin/pacstall-programs/pull/1) to see how well it will pass the tests. Tests with Debian and develop version of pacstall fail.

`optdepends` contains packages that are in non-free debian repo, which is disabled in tests, so the packages are unavailable. This doesn't break the process with pacstall master:

```
...
[+] INFO: Optional dependencies
[*] WARNING: libnvidia-encode1, intel-media-va-driver-non-free, libcuda1 does not exist in apt repositories
...
(build continues and succeeds)
```

but with develop it fails:

```
[+] INFO: Checking apt dependencies
	[>] libx11-6 ✓ [installed]
        <...>
	[>] libpulse0 ✓ [installed]
	[>] libnvidia-encode1 ✗ [required]
	[>] intel-media-va-driver-non-free ✗ [required]
	[>] libcuda1 ✗ [required]
[+] INFO: Optional dependencies
[*] WARNING: libnvidia-encode1, intel-media-va-driver-non-free, libcuda1 does not exist in apt repositories
			[0] Select none
		[1] libnvidia-encode1: Required to record your screen on NVIDIA 
		[2] intel-media-va-driver-non-free: Required to record your screen on Intel Broadwell or later iGPUs
		[3] libcuda1: Required to record your screen on NVIDIA
	Select optional dependencies to install [1 2 3 or Y] Y
[+] INFO: Selecting packages libnvidia-encode1 intel-media-va-driver-non-free libcuda1

(build continues, but in the end...)

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gpu-screen-recorder : Depends: libnvidia-encode1 but it is not installable
                       Depends: intel-media-va-driver-non-free but it is not installable
[!] ERROR: Failed to install gpu-screen-recorder deb
                       Depends: libcuda1 but it is not installable
	[+] INFO: Cleaning up
```

https://github.com/bibelin/pacstall-programs/actions/runs/11143605014

### To reproduce

Create a pacscript with optdepends that contains packages that are not available

### Expected behavior

Unavailable packages in `optdepends` don't break package building and installation (like in current master version)

### Screenshots

-

### OS version

Debian

### Pacstall version

develop

**Comment by oklopfer** [comment]
This is my next priority to solve. Thanks for the report
