### ISSUE TITLE
Do not reinstall "installed" packages with "pacstall -I"

### ISSUE THREAD

**Issue by mortim** [pacstall/pacstall#1282]
### Is your feature related to a problem? Please describe.

It seems like a good idea to avoid reinstalling "installed" packages.

### A clear and concise description of what you want to happen.

I want to install a package (for example: discord)
```sh
pacstall -PI discord-deb
```

but this package is already installed so pacstall prints to stdout something like this:
```
[discord] is already installed at version [VERSION]
```

**Comment by Elsie19** [comment]
So my solution won't actually halt installation, but it will instead print out a warning.
