### ISSUE TITLE
Add supports for RPM-based distros (such as Fedora and openSUSE)

### ISSUE THREAD

**Issue by jimed-rand** [pacstall/pacstall#1287]
### Is your feature related to a problem? Please describe.

Anyway, I don't have a problem in Pacstall usages. I just want to request it to available on RPM-based distros. 

### A clear and concise description of what you want to happen.

Anyway, Fedora is using DNF5 these times and openSUSE using zypper as main package manager for installing RPM packages. I want to add supports for any Linux distros which using DNF like Fedora, Mageia, RHEL, etc and add supports for zypper which only available on openSUSE. So, Fedora and openSUSE users could using Pacstall as alternative package manager. Also, I want to add supports in future updates to add pacscripts for RPM packages or for RPM-based distros I mentioned.

### Describe alternatives you've considered

I'm ready to help contribute and you can tell me what I can do for adding the supports I want above (because I am on Discord server, you can ping or tag me for advance the discussion there).

**Comment by Elsie19** [comment]
The last available version of pacstall to have support for RPM distros was 0.1.0 back in 2020, and that was a highly beta version.

On a more practical note to you, we won't ever support RPM distros. That's not our aim. Sorry.

**Comment by jimed-rand** [comment]
> The last available version of pacstall to have support for RPM distros was 0.1.0 back in 2020, and that was a highly beta version.
> 
> On a more practical note to you, we won't ever support RPM distros. That's not our aim. Sorry.

Fine, I'll fork the main repo into my own main repo and I'll give the supports on my own ways.

**Comment by Elsie19** [comment]
Can't wait to see it!
