### ISSUE TITLE
It is impossible to install 32-bit optional dependencies

### ISSUE THREAD

**Issue by rain1598** [pacstall/pacstall#157]
**Describe the bug**
Pacstall implements optional dependencies like this:
`printf "%s\n" "${optdepends[@]}" | cut -f1 -d":" | tr '\n' ' '`
However this also cuts out `i386` if the package is 32 bit
**To Reproduce**
Paste `echo "32bit-something:i386: this is something but in 32 bit" | cut -f1 -d":" | tr '\n' ' '` into shell or write a .pacscript with 32-bit `optdepends`

**Comment by D-Brox** [comment]
This can be fixed replacing `cut -f1 -d":"` with `awk -F': ' '{print $1}'`
We'll probably fix it after we merge the fakeroot branch.
