### ISSUE TITLE
Pacstall doesn't redownload scripts

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall#160]
**Describe the bug**
When downloading a pacscript, it won't overwrite the old script in `~/.cache/pacstall/` 

**To Reproduce**
Download a script, wait for an update to the script, and see that it won't overwrite the old file

**Expected behavior**
For it to redownload the script every time pacstall downloads a pacscript

**Desktop (please complete the following information):**

- OS + version: Linux Mint
- Pacstall Version + branch: develop

**Comment by wizard-28** [comment]
Concerning code block
```bash

if curl --output /dev/null --silent --head --fail "$URL" ; then
	mkdir -p "$HOME/.cache/pacstall" && cd "$HOME"/.cache/pacstall/
	mkdir -p "$PACKAGE" && cd "$PACKAGE"

	download "$URL" > /dev/null 2>&1
	return 0
else
	error_log 1 "get $PACKAGE pacscript"
	return 1
fi
```
