### ISSUE TITLE
Add option to purge

### ISSUE THREAD

**Issue by Korkmatik** [pacstall/pacstall#168]
**Is your feature request related to a problem? Please describe.**
Currently when uninstalling with `pacstall -R <package>` it will perform an `apt remove <package-gives>` if it is a deb package.

**Describe the solution you'd like**
 I think we could also add an option that will run `apt purge <package-gives>`. For example by running `pacstall -Rp <package>` or `pacstall -P <package>` or `pacstall --purge <package>`

**Describe alternatives you've considered**
Running `apt purge` manually

**Comment by Henryws** [comment]
Just so you know, the `-P` option is used for unattended installs (example: `pacstall -P -I neofetch`)

**Comment by Korkmatik** [comment]
> Just so you know, the `-P` option is used for unattended installs (example: `pacstall -P -I neofetch`)

Ok thank you!

**Comment by wizard-28** [comment]
How about `-R` purging by default?

**Comment by D-Brox** [comment]
It's possible now that we implemented the `apt` integration in 1.6

**Comment by Henryws** [comment]
We did this a while back.

**Comment by D-Brox** [comment]
#505
