### ISSUE TITLE
Fakeroot cannot open shared object file

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall#189]
**Describe the bug**
Whenever sudo is called within a pacscript, fakeroot outputs `ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.` This error does not affect whether or not the installation is successful

**To Reproduce**
Run any pacscript

**Expected behavior**
It doesn't do that.

**Screenshots**
![image](https://user-images.githubusercontent.com/70437021/129409176-ca20aef1-3952-419c-a295-084de842a00c.png)

**Desktop (please complete the following information):**

- OS + version: Pop!_os 21.04
- Pacstall Version + branch: 1.6 develop

**Comment by Henryws** [comment]
I believe the problem is that pacscripts are using sudo. 1.6 should prevent that from happening, provided pacscripts remove sudo references

**Comment by echometerain** [comment]
but pacscripts can't run without sudo
https://discord.com/channels/839818021207801878/866673569521991700/875054145663557632
