### ISSUE TITLE
Use $EDITOR as editor when editing a pacstall script

### ISSUE THREAD

**Issue by JonBoyleCoding** [pacstall/pacstall#20]
**Is your feature request related to a problem? Please describe.**
When editing a pacstall script via the option on an install, pacstall opens up nano to edit the script.

**Describe the solution you'd like**
Use $EDITOR environment variable if specified for editor.

**Describe alternatives you've considered**
A config somewhere could be used, but I would prefer the use of $EDITOR

**Comment by wizard-28** [comment]
Or we could use `editor <file_path>` to directly call the default system editor to edit things
