### ISSUE TITLE
deb package is broken.

### ISSUE THREAD

**Issue by kwon37xi** [pacstall/pacstall#223]
https://github.com/pacstall/pacstall/releases/download/1.5.1/pacstall-1.5.1.deb package contains wrong `pacstall` executable.
It contains no script code but `<html><body>You are being <a href="https://raw.githubusercontent.com/pacstall/pacstall/master/pacstall">redirected</a>.</body></html>` HTML content.

**Comment by Henryws** [comment]
Fixed
