### ISSUE TITLE
--force or --yes or -y option

### ISSUE THREAD

**Issue by kwon37xi** [pacstall/pacstall#224]
I made my own system restore script.
This script contains a lot of package install commands like `sudo apt install -y xxx`.
But because `pacstall` does not support `-y` or `--force` or `--yes` options, it is not easy to automate pacstall package installation.

Please add `force install/update/remove with default (yes) answers` option.

**Comment by NarutoXY** [comment]
There is already `-P` flag to disable prompts and auto install the packages

**Comment by kwon37xi** [comment]
Oh, thanks but there is no help about -P flag.

```
      options:
      -I --install, Installs package
      -Il --install-local, Installs a local package
      -S --search, Search for package
      -R --remove, Removes package
      -D --download, Downloads script
      -A --add-repo, Adds repo to your repo list
      -U --update, Update script
      -V --version, Prints pacstall version
      -L --list, Lists installed packages
      -Up --upgrade, Upgrades packages
      -Qi --query-info, Get package info
```
