### ISSUE TITLE
When archive file does not contains a directory, error occurs.

### ISSUE THREAD

**Issue by kwon37xi** [pacstall/pacstall#241]
**Describe the bug**
* some archive files don't contain a directory.
* When a archive file has no directory, install-local.sh shows an error.

**To Reproduce**
1. Just explain what happened and where you think the issue is
```
name="nerd-fonts-inconsolata"
pkgname="nerd-fonts-inconsolata"
pkgdir="${STOWDIR}/${name}"
description="Inconsolata Nerd Font"
version="2.1.0"
url="https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/Inconsolata.zip"
depends="fontconfig"
hash="21b2e09afb0fd7f0c06aba6605dae79abe1b7c9e695fc34d2232b43101e3eb91"
maintainer="KwonNam Son <kwon37xi@gmail.com>"

prepare() {
    true
}

build() {
    rm *Windows\ Compatible.*
    rm *.otf
}

install() {
    sudo install -d "${pkgdir}/usr/share/fonts/truetype/${name}"
    sudo install -Dm644 *.ttf "${pkgdir}/usr/share/fonts/truetype/${name}"
}

postinst() {
    fc-cache -vf
}

removescript() {
    fc-cache -vf
}
```
* "https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/Inconsolata.zip" - `Inconsolata.zip` file does not contain a directory. It just has files.
When I try to install this pacscript with develop branch  the following error occurs.
```
Inconsolata.zip              100%[==============================================>]  17.55M  9.28MB/s    in 1.9s
/usr/share/pacstall/scripts/install-local.sh: line 384: cd: ./*/: No such file or directory
```
**Expected behavior**
* no errors and install.

**Desktop (please complete the following information):**

- OS + version: Ubuntu 21.04
- Pacstall Version + branch: development version of 1.6, develop

**Comment by wizard-28** [comment]
Does the installation succeed even though the error is printed?

**Comment by kwon37xi** [comment]
Yes.

```
pacstall -Il nerd-fonts-inconsolata
Do you want to view/edit the pacscript [y/N]
[+] INFO: Sourcing pacscript
[+] INFO: URL exists
[+] INFO: Creating dummy package
Selecting previously unselected package nerd-fonts-inconsolata.
(Reading database ... 607421 files and directories currently installed.)
Preparing to unpack .../nerd-fonts-inconsolata-pacstall.deb ...
Unpacking nerd-fonts-inconsolata (2.1.0-1) ...
Setting up nerd-fonts-inconsolata (2.1.0-1) ...
[+] INFO: Installing dependencies
[+] INFO: Retrieving packages
Inconsolata.zip              100%[==============================================>]  17.55M  9.35MB/s    in 1.9s
/usr/share/pacstall/scripts/install-local.sh: line 384: cd: ./*/: No such file or directory
[+] INFO: Running prepare in fakeroot. Do not enter password if prompted
[+] INFO: Running build in fakeroot. Do not enter password if prompted
[+] INFO: Installing
[+] INFO: Symlinking files
.... blahblah...
fc-cache: succeeded
[+] INFO: Storing pacscript
[+] INFO: Cleaning up
```

**Comment by Henryws** [comment]
Yeah that's because it can't enter the directory. Its not a cause of concern, but we should probably redirect the output to /dev/null so it doesn't appear

**Comment by wizard-28** [comment]
Okay, so just appending `2> /dev/null` will fix(hide the error) it.

**Comment by kwon37xi** [comment]
That could be ok.
But how about give packagers an option to create package directory and unarchive the file into the created directory?
Because if just unarchive the file, the archive file(`Inconsolata.zip`) and it's contents(font files) are in the same directory(`/tmp/pacstall`).
It makes me confused.
