### ISSUE TITLE
/tmp/pacstall owner changed to root

### ISSUE THREAD

**Issue by kwon37xi** [pacstall/pacstall#244]
**Describe the bug**
With pacstall develop branch.

Whenever rebooting ubuntu, `/tmp` directory is cleared.
After rebooting and installing new package with pacstall, `/tmp/pacstall` is created with `root` permission.
Because of that dowloading files failed. downloading file is executed with user permission.

**To Reproduce**
1. reboot Ubuntu
2. install new package with pacstall.
3. You will see downloading files or cloning repository are failed.

**Expected behavior**
`/tmp/pacstall` must be owned by installing user account whenever try to install with pacstall.

**Desktop (please complete the following information):**

- OS + version: ubuntu 21.04
- Pacstall Version + branch: 1.6, develop branch

**Comment by NarutoXY** [comment]
`chown $USER /tmp/`

**Comment by wizard-28** [comment]
We should move that line to the script itself (instead of installer), so it'll happen automatically.
