### ISSUE TITLE
FR: read prepare section when url is a deb file

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#254]
**Is your feature request related to a problem? Please describe.**
I would like to make a pacscript for brave-browser, the release version

**Describe the solution you'd like**
For that to happen, I need to remove the "brave-keyring" dependency from the deb in the pacscript itself:
```bash
prepare() {
       ar x ${gives}_${version}_amd64.deb
       tar -xJf control.tar.xz
       sed -i s/", brave-keyring"//g control
       tar cfJ control.tar.xz control postinst prerm postrm
       ar rcs ${gives}_${version}_amd64.deb debian-binary control.tar.xz data.tar.xz
}
```

**Describe alternatives you've considered**
I tried to put the code in prepare(), build(), install(), but pacstall would first try to install the deb without considering any of the parts of the script

**Additional context**
Would be nice if pacstall would execute prepare(), and then install the modified (or unmodified) deb

**Comment by wizard-28** [comment]
Doesn't pacstall install the keyring alongside the `.deb`?

**Comment by Zahrun** [comment]
I think this deb is a useless one that they use just to make sure we install from their repo.
Never mind, I found the link to that deb in the repo, so I can use that.
