### ISSUE TITLE
Tool for converting arch-based pkgbuilds to pacstall scripts

### ISSUE THREAD

**Issue by ruzko** [pacstall/pacstall#263]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a possible improvement.

**Describe the solution you'd like**
I don't have experience contributing to pacstall, but I can imagine that a tool which converts pkgbuilds present in AUR to pacstall scripts could save a lot of maintainer effort. Especially when the pacstall repo grows.

**Describe alternatives you've considered**
Manually writing every pacstall script will work as well, but requires more effort in the long run to maintain a large number of packages.

**Comment by ruzko** [comment]
Apologies, I should have looked into it a bit more before opening an issue.

**Comment by wizard-28** [comment]
> Apologies, I should have looked into it a bit more before opening an issue.

No problem, and after all it was a prototype that we didn't advertise on the main README etc.
