### ISSUE TITLE
Pacstall isn't printing help if no options are given

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#27]
**Describe the bug**

Pacstall isn't printing the help menu when no options are provided (ex: `sudo pacstall`), instead it is printing the help menu when a `-` / `-h` is entered as a flag (ex: `sudo pacstall -` / `sudo pacstall -h`)

**To Reproduce**

1. Execute `sudo pacstall`, and see no help menu as an output (no output in fact)
2. Execute `sudo pacstall -` / `sudo pacstall -h` and see the help menu.

**Expected behavior**

Print the help menu when running `sudo pacstall`

**Screenshots**

In first screenshot there is no help menu
![no help menu](http://0x0.st/-2XE.png)
In second screenshot there is a help menu
![help menu](http://0x0.st/-2X6.png)

**Desktop (please complete the following information):**

- OS + version: Pop!_OS 20.04
- Pacstall Version: 1.2 `develop` branch

**Additional context**
I believe the problem is in this line
https://github.com/pacstall/pacstall/blob/e7ce4a6147e95ba478622b1d01660ea965771c1b/pacstall#L163-L164
Since pacstall is only entering the `while` loop when there is a `-` present in the command, this issue is occuring
https://github.com/pacstall/pacstall/blob/e7ce4a6147e95ba478622b1d01660ea965771c1b/pacstall#L169-L185
https://github.com/pacstall/pacstall/blob/e7ce4a6147e95ba478622b1d01660ea965771c1b/pacstall#L382-L385

**Comment by Henryws** [comment]
Yes, the problem is in that line, and the only way I can think of fixing this is by removing the `-P` flag with disables prompts for automated installations

**Comment by wizard-28** [comment]
Meh... we shouldn't sacrifice a feature to solve this minor bug... Let this issue be open, we will (or some other person) fix this problem in future

**Comment by Henryws** [comment]
For a more detailed explanation:
Pacstall uses `case` to filter arguments (flags), not `getopts`. Taking the command `sudo pacstall -P -I cmatrix`, pacstall will try to find the `-P` flag before all others (even if not given), and if so, will trigger the commands to read the default answer from each `ask` function, and use that is input. Then it will use the `shift` command to make pacstall run like `sudo pacstall -I cmatrix` instead of `sudo pacstall -P -I cmatrix`

**Comment by hwittenborn** [comment]
Would something like `"" | -h | --help)` work?

**Comment by NarutoXY** [comment]
Why are we chacking for ```^-``` ? We can just remove that line and make it 
```while [[ ! "$1" == "--" ]]; do ```

This way Pacstall will print help message even if someone types ```sudo pacstall example``` .
