### ISSUE TITLE
Bug: parallel pacstall installations fail

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#291]
**Describe the bug**
Installing a package with pacstall can take some time. If the user starts another pacstall installation in another terminal, both installations will fail.

**To Reproduce**
1. `pacstall -I ardour-git`
2. During compilation, in another terminal, `pacstall -I pdfmm-git`
Both installations happen in $SRCDIR
3. The pdfmm-git install fails to do `cd ./*/` and does a cleanup
4. The cleanup destroys ardour-git installation

**Expected behavior**
Prevent both installations to fail
Option 1: fail if another instance of pacstall is found running (or use a lock like dpkg does)
Option 2: have pacstall wait for the other install to finish
Option 3: try to allow parallel installations, do the installations in different directories eg. $SRCDIR/$PACKAGE

**Desktop (please complete the following information):**

- Kubuntu 21.04
- Pacstall 1.6 develop

**Comment by wizard-28** [comment]
We'll do this _after_ 1.6 gets released this week.
