### ISSUE TITLE
CI that will create assets for releases

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall#302]
**Is your feature request related to a problem? Please describe.**
Using [this](https://github.com/softprops/action-gh-release), we can create assets for our releases when a tag is created, meaning that can automate deb packages for Pacstall’s releases

**Describe the solution you'd like**
Add the github actions, modify to create debs on tag’s

**Describe alternatives you've considered**
Make deb’s by hand

**Comment by wizard-28** [comment]
> Using this, we can create assets for our releases when a tag is created, meaning that can automate deb packages for Pacstall’s releases

How will this work in Kournikova? No assets will be released. The build will be pushed to PyPI.

---

I guess we could automate pushing to PyPI (by changing this issue), what do you think?

**Comment by Henryws** [comment]
Yeah, we can create a CI that pushes to pypi when it detects a tag change

**Comment by wizard-28** [comment]
Closed in favor of #383
