### ISSUE TITLE
Build dependencies are not removed after install

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#313]
**Describe the bug**
Build dependencies are not removed after install

**To Reproduce**
1. Install a package having build dependencies
2. Answer `y` to the question `Do you want to remove them after installing $PACKAGE [y/N] y`
3. Install succeeds
4. Build dependencies are not removed

**Expected behavior**
Build dependencies are removed

**Desktop (please complete the following information):**
- Kubuntu 21.10
- Pacstall 1.6 master

**Comment by Henryws** [comment]
what package did you install?

**Comment by Zahrun** [comment]
I was working on a local pacscript.
Here is an exemple in main repo that shows the issue:
`pacstall -I obs-backgroundremoval-git`
libobs-dev is not install before but stays installed after
