### ISSUE TITLE
Let users choose which optional dependencies to install

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall#339]
**Is your feature request related to a problem? Please describe.**
Pacstall only offers a yes or no prompt for installing all optional dependencies

**Describe the solution you'd like**
Either bind each dependency to a number/letter and let the user choose which one (and a letter for `install all`), like in yay, or asking the user one by one.

**Describe alternatives you've considered**
Maybe GUI checkboxes would be better?

**Comment by wizard-28** [comment]
> Either bind each dependency to a number/letter

I guess this would be better. How would you want the information to be printed out? Like this?
```
Optional dependencies for vlc
    0. Default: ALL
    1. avahi: for service discovery using bonjour protocol [installed]
    2. libnotify: for notification plugin [installed]
    3. ncurses: for ncurses interface support [installed]
    4. libdvdcss: for decoding encrypted DVDs
    5. lirc-utils: for lirc plugin
    6. libavc1394: for devices using the 1394ta AV/C [installed]
    7. libdc1394: for IEEE 1394 plugin [installed]
    8. kdelibs: KDE Solid hardware integration
    9. libva-vdpau-driver: vdpau back-end for nvidia
    10. libva-intel-driver: back-end for intel cards
    11. libbluray: for Blu-Ray support [installed]
    12. flac: for Free Lossless Audio Codec plugin [installed]
    13. portaudio: for portaudio support
    14. twolame: for TwoLAME mpeg2 encoder plugin
    15. projectm: for ProjectM visualisation plugin
    16. libcaca: for colored ASCII art video output [installed]
    17. libgme: for libgme plugin [installed]
    18. librsvg: for SVG plugin [installed]
    19. gnome-vfs: for GNOME Virtual File System support
    20. libgoom2: for libgoom plugin
    21. vcdimager: navigate VCD with libvcdinfo
    22. aalib: for ASCII art plugin [installed]
    23. libmtp: for MTP devices support [installed]
    24. smbclient: for SMB access plugin [installed]
    25. libcdio: for audio CD playback support [installed]
    26. ttf-freefont: for subtitle font 
    27. ttf-dejavu: for subtitle font
    28. opus: for opus support [installed]
    29. libssh2: for sftp support [installed]
    30. lua-socket: for http interface
```

Also how would the user enter their choice? What will be the delimiter? A space?
Example:
```
Enter your choice (space separated): 1 25 30
```

**Comment by echometerain** [comment]
yeah, I would recommend using 0-9 and then a-z for the choices though to save typing time, like:

```Enter your choice (space separated): 1 8 f h```


0 or [enter] is a good choice for `install all`

**Comment by wizard-28** [comment]
> yeah, I would recommend using 0-9 and then a-z for the choices though to save typing time,

How would it save typing time?

> 0 or [enter] is a good choice for install all

So how about this?
```
Optional dependencies for vlc
   -1. Don't install anything
    0. Install all or just press enter
    [...]
```

**Comment by echometerain** [comment]
just a dash is ok
```
Optional dependencies for vlc
    -. Don't install anything
    0. Install all or just press enter
    [...]
```

**Comment by wizard-28** [comment]
> just a dash is ok
> 
> ```
> Optional dependencies for vlc
>     -. Don't install anything
>     0. Install all or just press enter
>     [...]
> ```

How about replacing `0` with `+`, since we are using `-` for not installing anything?

This also forms a visual separation between the mutually separate options (`+` and `-`, installing everything and not installing everything) and the multiple choice ones (the dependencies)

**Comment by echometerain** [comment]
sure!

**Comment by Henryws** [comment]
Done in `3.0.0`!
