### ISSUE TITLE
Create FAQ section in the wiki

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#356]
A FAQ section under the Pacstall section would be good.

_Originally posted by @wizard-28 in https://github.com/pacstall/pacstall/discussions/355#discussioncomment-1664681_

**Comment by wizard-28** [comment]
Some changes:
> Pacstall and Makedeb attempt to fix the same problem: The lack of up to date packages on Ubuntu.

[Pacstall](https://github.com/pacstall/pacstall) and [Makedeb](https://github.com/makedeb/makedeb) attempt to fix the same problem: The lack of up to date packages on Ubuntu.

I think Makedeb tries to solve the problem for Debian specifically. Not for Ubuntu. Change the above sentence to reflect this.

---

> Where Pacstall and Makedeb divert are in method of distribution, and packaging.

Where [Pacstall](https://github.com/pacstall/pacstall) and [Makedeb](https://github.com/makedeb/makedeb) divert is in the method of distribution, and package installation.

---

> Makedeb uses a [centralized service](https://mpr.hunterwittenborn.com) while Pacstall can be used without a centralized service, but defaults to our main repository.

Makedeb uses a [centralized service](https://mpr.hunterwittenborn.com) while Pacstall can be used without a centralized service, but defaults to [our main package repository](https://github.com/pacstall/pacstall-programs) (Use `-A` command to add your personal repository to `pacstall`'s repo list).

**Comment by Henryws** [comment]
I pushed the changes, your thoughts?

**Comment by wizard-28** [comment]
> I pushed the changes, your thoughts?

All the changes are not pushed? Why?

---

> Well what about universal packaging methods like AppImages, Snaps, and Flatpaks?

### Well what about universal packaging methods like AppImages, Snaps, and Flatpaks?

---

The whole explanation is very confusing and wrong in some parts. Also no line breaks. Only robots can read documents with no line breaks.

> We support AppImages in Pacstall, as they aren’t technically a packaging system, and more of just a universal method of executing software the same on all Linux distributions.

They are a universal packaging system.

> Next are Snaps.

Write this section in a separate paragraph.

> They are awful in every way possible: They make ~/snap, they use mount points, they slow down system startup, they only have one store, they have awful theming support, and are only really made for Ubuntu in mind.

You know this is an FAQ, not a discord conversation with the reader and you?

How about:
```
They have many problems
1. They create `~/snap`. ( I've never seen this mentioned anywhere, are you sure this is factually correct?)
2. They create mount points for every snap application.
3. They are way slower than native apps when it comes to startup time.
4. They have a main [proprietary store/server](https://snapcraft.io/), although there is [an ongoing effort for a open source one](https://repo.lolsnap.org/lol-snap/lol)
5. They do not integrate well with your theming and look foreign in your desktop environment.
6. They are notoriously difficult to uninstall, especially the snap daemon.
7. They update the applications automatically by default, unless you go out of your way to disable this behavior.
```

List more problems if you find more on the internet.

---

> Flatpaks now. They are the objectively best universal packaging method, as they have minimal overhead on the system, have decent theming support, are endorsed by many distributions, can have multiple “stores”, and integrate with the system way better than Snaps. The final point is that Flatpaks and Snaps are not native packages. They both run in a containerized environment, which makes them by definition slower than native packages, like anything installed with Pacstall.

Next

**Comment by Henryws** [comment]
Shall I close this?

**Comment by wizard-28** [comment]
> Shall I close this?

No... This will still be there until the docs are moved over to Antora

**Comment by hwittenborn** [comment]
Any update on this? I'd love to see the docs get moved to <https://docs.pacstall.dev> or something.

**Comment by wizard-28** [comment]
> Any update on this? I'd love to see the docs get moved to https://docs.pacstall.dev or something.

We'll probably use ReadTheDocs instead of Antora as it's more integrated with the python ecosystem.

**Comment by csehszlovakze** [comment]
I came across this project thanks to a recent DistroTube video. After reading through most of the documentation, I still have a question: is an Ubuntu base a hard dependency, or does this also work with Debian and Devuan? (I'm mostly interested in the latter.)

**Comment by Henryws** [comment]
No, Ubuntu is not a hard dependency. I use debian and the vast majority of packages work just fine on debian. There are a couple packages that have missing/outdated/different named dependencies for debian packages, but overall, yeah, pacstall is usable on debian 99% of the time.

**Comment by Henryws** [comment]
I created the relevant section in the FAQ.
