### ISSUE TITLE
Create a usage section in the Wiki

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#370]
The multiple ways to install packages (choosing repo, local install, prompless and keep etc)

_Originally posted by @D-Brox in https://github.com/pacstall/pacstall/discussions/355#discussioncomment-1674954_

**Comment by Henryws** [comment]
This should be kept to the man page or on the main README.md

**Comment by wizard-28** [comment]
> This should be kept to the man page or on the main README.md

We remove that section from our readme, and put a link there instead.

Like this:
![img](https://0x0.st/-7s7.png)

**Comment by Henryws** [comment]
I feel like *some* sort of usage should be presented on the main README

**Comment by wizard-28** [comment]
> I feel like _some_ sort of usage should be presented on the main README

How about we list all the command syntaxes in README, with their short description, but link to the wiki for the more thorough in-depth description

**Comment by Henryws** [comment]
Yes, that would be fine

**Comment by D-Brox** [comment]
It would be good for the wiki to explain the commands that are more complex, like `pacstall -I pkgname@user/repo`
