### ISSUE TITLE
Completions are partly broken

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#371]
**Describe the bug**

After #330 was merged the completions seem to be broken.

---

`bash`:
 1.`-K*` for `bash` shell is broken, instead of completions other flags are shown.

`fish`:
1. All `-Il` flags when tabbed with no `.pacscript` file present error out.
---

**To Reproduce**

`bash`:
This is the procedure to demonstrate broken behavior for `-KI`
1. Type out `pacstall -KI` in terminal
2. Press tab
3. See that flags are suggested instead of packages.
![img](https://0x0.st/-7zc.png)

`fish`:
This is the procedure to demonstrate broken behavior for `-Il` when no `.pacscript` is present
1. Ensure no `.pacscript` is present in `cwd`
1. Type out `pacstall -Il`
2. Press tab
3. See fish error out.
![img](https://0x0.st/-7zT.png)

**Expected behavior**

The completions work correctly.

**Desktop (please complete the following information):**

- OS + version: [e.g. Ubuntu 20.04]: Pop!_OS 20.04
- Pacstall Version + branch: [e.g. 1.1 master]: 1.6.2 `develop`

**Comment by echometerain** [comment]
shoot
