### ISSUE TITLE
Give user option to use `stow --adopt` when stow encounters a conflict

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall#391]
**Is your feature request related to a problem? Please describe.**
If I build a large program and the files cause a conflict, I have to start the process all over again

**Describe the solution you'd like**
Give user option to use `--adopt` (in stow) when stow encounters a conflict (through the `ask` function)

**Comment by wizard-28** [comment]
What should this option do?

**Comment by Henryws** [comment]
It's like `keep`, but for stow conflicts

**Comment by wizard-28** [comment]
So it'll ignore the stow conflict?

**Comment by Henryws** [comment]
Yes

**Comment by wizard-28** [comment]
I thought keep does what is being described here?

Can you explain in  detail what keep and what you're proposing do again (and do differently)?

**Comment by D-Brox** [comment]
We'd need to log and add it to the metadata that it failed

**Comment by echometerain** [comment]
If stow encounters a conflict between the stow directory and the system files, lets say stow wants to symlink `$STOWDIR/$name/usr/bin/smth` to `/usr/bin/smth` but `/usr/bin/smth` already exists, stow halts immediately and I would have to build the entire program again. What I'm suggesting is to list the files in conflict and ask the user if they want to let stow replace the files on their disk. If the user answers `Y` (default `N`), pacstall runs `stow --adopt` instead of regular stow.

**Comment by wizard-28** [comment]
> If stow encounters a conflict between the stow directory and the system files, lets say stow wants to symlink `$STOWDIR/$name/usr/bin/smth` to `/usr/bin/smth` but `/usr/bin/smth` already exists, stow halts immediately and I would have to build the entire program again. What I'm suggesting is to list the files in conflict and ask the user if they want to let stow replace the files on their disk. If the user answers `Y` (default `N`), pacstall runs `stow --adopt` instead of regular stow.

And adopt overwrites those files right?

**Comment by echometerain** [comment]
yeah

**Comment by echometerain** [comment]
this is not adding an option to pacstall, this is for pacstall to prompt the user if they want to run `stow --adopt`

**Comment by wizard-28** [comment]
Good idea, scheduling it for Kournikova!

**Comment by wizard-28** [comment]
We'll likely not use stow directly, but replicate it's functionality in Python, and add the overwtiting functionality you suggested.

**Comment by Henryws** [comment]
We don't use Stow anymore.
