### ISSUE TITLE
Switch to Conventional Commits for commit messages

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#397]
It appears so that our current commit message specification in the [CONTRIBUTING.md](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md#commits) is really a botched [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) scheme.

So, let's switch to it.

There is a `pre-commit` (`commit-msg` stage) hook for validating this scheme. Adding it to #390

**Comment by wizard-28** [comment]
[Commitzen](https://github.com/commitizen-tools/commitizen), seems to be the golden tool for #390, #383 and #358, and this.

It handles commit validation/creation (also has pre-commit hook), bumps versions (for semantic versioning), and changelog generation plus can create releases and push to PyPI, on configuring the CI with it.

**Comment by Henryws** [comment]
Since we are using this currently, should this be closed?

**Comment by wizard-28** [comment]
> Since we are using this currently, should this be closed?

@Henryws, no it's not added to the `CONTRIBUTING.md` yet. Once `python3-rewrite` gets merged to develop, I'll then edit it.

**Comment by Henryws** [comment]
How about now 🥺
