### ISSUE TITLE
Remove two letter `-` flags in favour of lowercase flags (for pyRewrite)

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall#400]
**Is your feature request related to a problem? Please describe.**
Two letter flags with a single dash is generally a bad idea.

**Describe the solution you'd like**
I know `-Il` functionality has been included in `-I` already (rewrite)

- replace `-Up` with `-u`
- replace `-Qi` with `-q`

**Comment by Henryws** [comment]
>  Two letter flags with a single dash is generally a bad idea.
Any reason why we should break basic compatibility?

**Comment by echometerain** [comment]
because it would look nicer

maybe

**Comment by Henryws** [comment]
I don't think breaking the most basic compatibility for the sake of it looking nice (which is objective) is a good idea
