### ISSUE TITLE
Change directories for storing data

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall#406]
**Is your feature request related to a problem? Please describe.**
Files stored in /var/log are usually temporary, for pacstall however, it's not. When I was cleaning my system with bleachbit, it automatically deleted `/var/log/pacstall/metadata` which causes pacstall to not recognize *any* installed pacstall programs.

**Describe the solution you'd like**
Move `/var/log/pacstall/metadata` to `/var/lib/pacstall/metadata`

**Other directories to change**
Move `/tmp/pacstall` to `/var/cache/pacstall`

**Comment by wizard-28** [comment]
![filesystem](https://preview.redd.it/j2k4k1j6f1x71.jpg?width=960&crop=smart&auto=webp&s=37b533281b6aad2285cd6d4875ae0c8f9aa15304)

We can follow the guidelines here. So for this we could move it to `/var/lib/pacstall/metadata`

**Comment by echometerain** [comment]
yeah

**Comment by wizard-28** [comment]
Also, how about we move `SRCDIR` from `/tmp/pacstall` to `/var/cache/pacstall`?

**Comment by echometerain** [comment]
sure

**Comment by Henryws** [comment]
@wizard-28 any updates, or should this be closed as wontfix?
