### ISSUE TITLE
Incorrect message file path on download

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall#407]
**Describe the bug**
During the download of a package with the `-D` flag, Pacstall reports the Pacscript was downloaded to `$HOME/$name`, which gives the impression of a directory, when the Pacscript was really downloaded to `$HOME/${name}.pacscript`.

**To Reproduce**
Install Pacstall
Download any script using `-D`
Observe the incorrect download message

**Expected behavior**
A download message such as
```bash
[+] INFO: ${name}'s pacscript is downloaded to /home/henry/${name}.pacscript
```

**Screenshots**
![image](https://user-images.githubusercontent.com/58742515/146678161-676da938-1397-4b2c-a8a4-7929ec8e3572.png)

**Desktop (please complete the following information):**

- OS + version: Debian Sid
- Pacstall Version + branch: 1.7 Develop

**Comment by D-Brox** [comment]
This should be in the 1.7.1 bugfix
