### ISSUE TITLE
`-Il` completes with `.pacscript` extension

### ISSUE THREAD

**Issue by echometerain** [pacstall/pacstall#409]
**Describe the bug**
`pacstall -Il ardour` completes with `pacstall -Il ardour-git.pacscript` instead of `pacstall -Il ardour-git` on zsh. Have not tested with fish.

**To Reproduce**
1. Download a pacscript
2. Complete it with zsh

**Expected behavior**
For it to complete without the `.pacscript` extension

**Screenshots**
![image](https://user-images.githubusercontent.com/70437021/146766091-0edf67f0-fac7-4103-a313-2930faa84b95.png)

**Desktop (please complete the following information):**

- OS + version: Ubuntu 21.10 impish
- Pacstall Version + branch: 1.7 master

**Additional context**
Please test on fish

**Comment by wizard-28** [comment]
> ardour-git.pacscript

I can confirm it doesn't happen in `fish`

**Comment by echometerain** [comment]
this only happens on ubuntu, which uses a different versionn of zsh
