### ISSUE TITLE
Explain the "held back" message in FAQ

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#425]
> Pinning is probably the best option, because version hacking could actually mess with other packages that depend on the dummy deb. Pinning would fix this issue very easily and it's less hacky.

We should include a note in our FAQ explaining the `The following packages have been kept back:` message then.

_Originally posted by @wizard-28 in https://github.com/pacstall/pacstall/issues/423#issuecomment-1000460489_

**Comment by Henryws** [comment]
Not needed due to #432
