### ISSUE TITLE
Broken version checker with `-V` flag

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall#427]
**Describe the bug**
The version printer with the `-V` flag has long been broken and the method of retrieving the version is very fragile and prone to failure

**To Reproduce**
Install pacstall
Install a package (brave-browser-beta-deb)
Run `pacstall -V brave-browser-beta-deb`

**Expected behavior**
For the method of retrieving the version to be less fragile

**Desktop (please complete the following information):**

- OS + version: Debian Sid
- Pacstall Version + branch: 1.7 Develop

**Comment by wizard-28** [comment]
This functionality is already depreciated IIRC, if not it'll be for Kournikova.

**Comment by Henryws** [comment]
Since this is the last bash release, I strongly recommend we fix this, as it's a simple thing to do.

**Comment by wizard-28** [comment]
wontfix as this will be removed in Kournikova
