### ISSUE TITLE
Add a `preinstall()` hook

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#428]
**Is your feature request related to a problem? Please describe.**
Currently we can't package programs such as [Nala](https://gitlab.com/volian/nala) as they have their own third party repository which contains the required dependencies for the package.

**Describe the solution you'd like**
Add a `preinstall()` hook that runs at first, even before the metadata gets evaluated (therefore it runs even before `prepare()`). By doing so we could add the repository to the system first, which then helps `apt` resolve the `dependencies` later on.

**Describe alternatives you've considered**
Adding another metadata, maybe a `repo` array where we specify the third party repository, and their signing keys, and Pacstall does some magic to install the `repo`. I think we shouldn't do this as this method is complicated and not very flexible.

**Additional context**
None.

**Comment by hwittenborn** [comment]
Shouldn't all needed dependencies just be included in the Pacstall repository? Adding external repositories during the build process (or really any step) sounds like a bad idea to me.
