### ISSUE TITLE
Explain issues related to pinning in the wiki

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#441]
Issues like:
1. ![](http://0x0.st/osep.png)
2. And others, I don't remember all of them

**Comment by Henryws** [comment]
When installing a package through Pacstall, this error will come up when trying to install that same package through apt:
![image](https://user-images.githubusercontent.com/58742515/147951650-54840c4b-88b3-4861-9509-1c03619e59a6.png)
Remove the package with Pacstall and then install the apt package again.

**Comment by wizard-28** [comment]
Done
