### ISSUE TITLE
Switch from the current stowing system to a deb system.

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#467]
Everything will be better. No more `sudo`s in files, better system integration than creating a dummy deb. Code will be cleaner (no need to do 2 things anymore, just focus on deb). People won't be mad etc.

**Comment by cat-master21** [comment]
I have to +1 this issue because other projects can package their projects as Makedeb has this feature like with Polymc: https://github.com/PolyMC/PolyMC/issues/93.

**Comment by Henryws** [comment]
This will be implemented in Cobalt (version after 2.0.0 Apricot). However Cobalt will use Pacscript + Deb, while Kournikova will use PKGBUILD + Deb.
