### ISSUE TITLE
Switch to a toml config file

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#470]
This file would be placed in `/etc/pacstall/config.toml`, and will be used to configure pacstall settings. This will be a single file to configure the whole of pacstall.

Currently these settings are planned to be user configurable
1. Repo list: pacstall/pacstall#450 
2. Jobs count: pacstall/libpacstall#11 
3. Preferred editor: pacstall/libpacstall#12

**Comment by wizard-28** [comment]
Superseded by https://github.com/pacstall/libpacstall/issues/4

**Comment by Elsie19** [comment]
Closed until @wizard-28 is active again.
