### ISSUE TITLE
pacstall lists no installed package after log folder purge

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#474]
**Describe the bug**
`pacstall -L` lists no installed packages after pacstall update

**To Reproduce**
1. Install packages with pacstall
2. Update pacstall to more recent version
3. `pacstall -L` lists no installed packages

**Expected behavior**
pacstall should remember what packages were installed, even after an update

**Screenshots**
![image](https://user-images.githubusercontent.com/10415894/150470230-1a4171bd-b967-4f6e-a8ea-a6bede1299db.png)

**Desktop (please complete the following information):**

- OS + version: Kubuntu 21.10
- Pacstall 1.7.1 master

**Additional context**
Noticed this issue after updating to 1.7 so reinstalled all the packages
Then again same issue after updating to 1.7.1

**Comment by wizard-28** [comment]
What's the output of:
```bash
/bin/ls -1aA "/var/log/pacstall/metadata"
```

**Comment by Zahrun** [comment]
Oh yes I understand what happened now.
![image](https://user-images.githubusercontent.com/10415894/150471286-cc942a0c-2b9f-4ed5-adac-c95fb83ce593.png)
Purging log folder will remove pacstall metadata
Can we move the important pacstall data out of the log folder (only logs should be there)?

**Comment by wizard-28** [comment]
Yes we have it planned https://github.com/pacstall/pacstall/issues/406
