### ISSUE TITLE
Installing multiple apps at once

### ISSUE THREAD

**Issue by LinuxSBC** [pacstall/pacstall#51]
When I try to install multiple apps using something like `sudo pacstall -I neofetch micro other-app` pacstall only installs the first in the list. There are no warnings or messages, it just only installs the first, in this case neofetch. This is unlike the behavior of every other package manager that I have used and can be annoying. Adding some way of installing multiple apps would be very helpful. 
Steps to reproduce:
1. Install pacstall.
2. Run `sudo pacstall -I` with more than one argument.
This will only install the first item in the list of arguments.

Thank you.

**Comment by erikLundstedt** [comment]
I might add a whay to do multiple installs thru pacget in the meantime
maybe using something like a forloop or xargs

cant promise much though as I`m not sure how to do it with the ui thing im using

**Comment by Henryws** [comment]
Well I know that running `echo $*` after the commands have input will output something like `-I vim` and we could cut the `-I` from it. If it is a `-P -I`, we could cut that also

**Comment by Henryws** [comment]
So more stuff, something like this could work:
```bash
#!/bin/bash
PACKAGE=$*
echo $PACKAGE | cut -dI -f2- | sed 's/ //'
```
It would take all input and echo it out, cutting to the first `I`, which would be the `-I`, then deletes the first space left over. Then it could take the rest of the inputs as a for i in statement

**Comment by Henryws** [comment]
I made a branch with basic multi command. The one compromise is that it removes the text that tells you where your script is if your running the `-D` flag
