### ISSUE TITLE
aomp-deb: cannot find patches

### ISSUE THREAD

**Issue by cat-master21** [pacstall/pacstall#512]
**Describe the bug**
Aomp-deb cannot find patches

**To Reproduce**
Simply do `pacstall -I aomp-deb`

**Expected behavior**
Notice aomp-deb cannot find patch.

**Desktop (please complete the following information):**
 - OS: Kali GNU/Linux Rolling
 - Version: 2022.1

**Additional context**
After testing, there isn't a patch folder or just patch, unlike what https://github.com/pacstall/pacstall/wiki/Pacscript-101#patch said there should a PACSTALL_patchesdir folder.

**Comment by Henryws** [comment]
I figured out the issue is that `postinst` for debs run before `patch`. The best option is to make the patch downloader into a function and put it before the download.
