### ISSUE TITLE
Make pacdeps look in local packages

### ISSUE THREAD

**Issue by sarmong** [pacstall/pacstall#539]
### Describe the bug

I am creating a `pacscript` for `rofi` package and it requires `check` package.

Since, it requires newer version of `check` then the one in Ubuntu repo, I need to build it myself.

For that, I created `check.pacscript`, installed it and put `pacdeps=("check")`

Get the following error

```
[*] WARNING: There is no package with the name check
[!] ERROR: Failed to install pacstall dependencies
```

### To reproduce

1. Install `check` with [this script](https://github.com/sarmong/pacstall-sarmong/blob/master/check/check.pacscript)
2. Download [rofi script](https://github.com/sarmong/pacstall-sarmong/blob/master/rofi/rofi.pacscript)
3. Uncomment `pacdeps=("check")` line
4. Try to install rofi
5. Behold the error

### Expected behavior

Pacstall looks in installed packages as well

### Screenshots

-

### OS version

Ubuntu 20.04

### Pacstall version

1.7.2

**Comment by wizard-28** [comment]
You need to add the `check` package to the pacstall repositories first by making a PR [here](https://github.com/pacstall/pacstall-programs), then work on your `rofi` script.

**Comment by D-Brox** [comment]
Actually, you can just change the structure of your [repo](https://github.com/sarmong/pacstall-sarmong).

Add a `packagelist` file at the root and put the directories you currently have inside a `packages` directory:
```
package-repository/
├── packagelist
└── packages/
    └── example-package/
        └── example-package.pacscript
 ```
 
 Then just add your repo to your `repolist` with `pacstall -A https://github.com/sarmong/pacstall-sarmong`. Pacstall will then be able to search on your repo and find `check`

**Comment by wizard-28** [comment]
> Actually, you can just change the structure of your [repo](https://github.com/sarmong/pacstall-sarmong).
> 
> Add a `packagelist` file at the root and put the directories you currently have inside a `packages` directory:
> 
> ```
> package-repository/
> ├── packagelist
> └── packages/
>     └── example-package/
>         └── example-package.pacscript
> ```
> 
> Then just add it to your `repolist` with `pacstall -A https://github.com/sarmong/pacstall-sarmong`. Pacstall will then be able to search on your repo and find `check`

They are talking about local pacdeps though, not from a repository.

**Comment by wizard-28** [comment]
Marking this as invalid as @Henryws requested.

**Comment by D-Brox** [comment]
True, we need to add a check to see if it's installed
> https://github.com/pacstall/pacstall/blob/db7206ed3650e3f757cb1f6c4e05fd9b5fae9d58/misc/scripts/install-local.sh#L339-L353

But still, fixing the structure of the repo and adding it to the `repolist` would fix the issue.
