### ISSUE TITLE
Pacscript is not updated

### ISSUE THREAD

**Issue by sarmong** [pacstall/pacstall#544]
### Describe the bug

When I update pacscript for the package in a custom repo, `pacstall` still uses an old version of the script even after running `pacstall -U`

### To reproduce

1. Create package repo and add a script there
2. Add it with `pacstall -A url`
3. Update some field in a package
4. Push the changes
5. Run `pacstall -U`
6. Run `pacstall -I package`
7. Behold that an old pacsript is being used

### Expected behavior

`pacstall -U` updates all repos with new pacscripts

### Screenshots

-

### OS version

Ubuntu 20.04

### Pacstall version

1.7.2

**Comment by wizard-28** [comment]
The command to update scripts is `-Up`, not `-U`

**Comment by sarmong** [comment]
So, as I understand, there is currently no way to just update the package info without upgrading the packages themselves?

**Comment by D-Brox** [comment]
Github takes a few minutes to propagate commits. That may be what happened to you when you tried to upgrade. Upgrade always fetches the newest version of the pacscript, but the change on github usually takes up to 5 minutes to occur.

We are planning on implementing a cache system for our python release. 
Currently, the `-U` flag updates just the pacstall installation, but this not be the behaviour in 2.0.0, as we are moving to a command structure closer to `apt` and `nala`.

` here is currently no way to just update the package info and package list without upgrading the packages `
The `packagelist` files are currently fetched on demand. The package info you get from the `-Qi` flag only shows the info from installed packages. This would change with the future implementation of a cache system tho.
