### ISSUE TITLE
Support for installing into the XDG Home directories

### ISSUE THREAD

**Issue by Fuseteam** [pacstall/pacstall#56]
**Is your feature request related to a problem? Please describe.**
Ubuntu Touch is a derivative of Ubuntu that ships with an readonly rootfs, as such many paths like /usr /bin /var etc are not writable by default, i would like to make use of pacstall on it

**Describe the solution you'd like**
i would love to see pacstall support installing into the XDG Home directories, that .config, .local/share and .cache, an additonal benefit of this will be that pacstall will be no longer dependend on sudo improving security. a side effect will be that we'll need to add .local/share/pacstall/bin to path or find a way to make it findable

**Describe alternatives you've considered**
inspired by your work i am somewhat working on [crackle](https://github.com/fuseteam/crackle) which wraps apt to work with a readonly rootfs and installs packages into ~/.local/share/crackle. this approach works for simple binaries but runs into issues when the application is search for /usr, /etc and such, with pacstalls method of compiling we should be able to set the prefix to .local/share/pacstall

**Comment by Henryws** [comment]
Sounds good, but here's the problem: Binaries are fickle and it's best just to leave everything as it should be. The only reason pacstall uses stow is that it works, with minimal issues. It just symlinks files. What you want is to wrap apt?? (Pacstall installs dependencies with apt, nothing else). I don't get it. Help me out

**Comment by Fuseteam** [comment]
no no i'm not asking you to make pacstall wrap app but rather a way to let it install into xdg home directories instead of root
i have gotten a few apt working like that, and that's without recompiling, i have feeling many more can work with recompiling with a set prefix

**Comment by Henryws** [comment]
You mean instead of `sudo make install DESTDIR=/usr/src/pacstall/pkg`, you want `make install DESTDIR=$HOME/.whatever`?

**Comment by Henryws** [comment]
Why would pacstall need to support Ubuntu touch?

**Comment by Fuseteam** [comment]
why not? :P apt is pretty much useless with a readonly rootfs it could expand the amount of apps that are usable on the terminal on ubuntu touch. and uh ubuntu touch can work on the desktop as well........one day

**Comment by Henryws** [comment]
The question is why, not why not. I don't want to support a trivial OS that does not work well with desktop apps (which is what most of pacstall has). Binaries say something like: `I want this file in this specific directory`, and using some hackish method to get it to work in the home directory doesn't work well

**Comment by Fuseteam** [comment]
it can work with desktop apps fine, it the only hurdle it is that the rootfs is not writable by default, my understanding so far is that binaries can be compiled with to prefix, so that search for the files in said prefix, tho that understanding comes mostly from https://itch.io/docs/itch/appendix/building-into-a-prefix.html
i'm not going to ask for official support, all i'm hoping for is a variable or switch to get pacstall to do a prefix install if possible

**Comment by Henryws** [comment]
`i'm not going to ask for official support, all i'm hoping for is a variable or switch to get pacstall to do a prefix install if possible`: That's asking for support.
Also what about the programs that require things to be in a specific place? Then their out of the question.

**Comment by Fuseteam** [comment]
`Also what about the programs that require things to be in a specific place? Then their out of the question.`
my current understanding is that they can be told to look in the prefix directory, if they are build into a prefix.
how many programs that can cover i have no idea, but i think its worth looking into

**Comment by Henryws** [comment]
Pacstall installs to `/usr/src/pacstall` That's the way it is. You could edit pacstall to install to the home directory and edit the script accordingly, but I can't help you with Ubuntu Touch

**Comment by Fuseteam** [comment]
guess that's fine, thanks for your time

**Comment by Fuseteam** [comment]
just to confirm: is my understanding correct that pacstall installs everything into /usr/src/pacstall and symlinks the files to the "right" places?

**Comment by Henryws** [comment]
If there is a package called `pkg`, Pacstall will install said package to `/usr/src/pacstall/pkg` and symlink it to `/`

**Comment by Fuseteam** [comment]
hmmm interesting
