### ISSUE TITLE
Running update with Pacstall breaks the terminal on Pop!_OS 22.04 Beta. 

### ISSUE THREAD

**Issue by RayJW** [pacstall/pacstall#571]
### Describe the bug

Sometimes when running `pacstall -U` the terminal output is broken, and it causes the terminal to behave weirdly by shifting all terminal output. It happens maybe 7/10 times. I've confirmed this behaviour on 3 different installs and with multiple terminal emulators like "Gnome Terminal" or "Alacritty". 
It is easily fixed with `reset` but when ran in combination with a script like "[Topgrade](https://github.com/r-darwish/topgrade)" it essentially breaks everything that is being run after it. 

### To reproduce

1. Just run `pacstall -U` until it happens. 

### Expected behavior

A proper output every time it is run. 

### Screenshots

![Broken behaviour](https://user-images.githubusercontent.com/29835902/163559153-178491d8-c082-4027-9e47-d623d33ec68f.png)
![Expected behaviour after running the command for ~10 times and broken behaviour immediately after](https://user-images.githubusercontent.com/29835902/163559359-01d39b84-29fc-4315-800a-f4e9e92d0c5a.png)

### OS version

Pop!_OS 22.04 Beta

### Pacstall version

1.7.3 but also happened with 1.7.2

**Comment by D-Brox** [comment]
I've seen this happen before with another user, but wasn't able to replicate it in my machine. I'll try it in a VM, it may be a Ubuntu 22.04 only bug

**Comment by RayJW** [comment]
> I've seen this happen before with another user, but wasn't able to replicate it in my machine. I'll try it in a VM, it may be a Ubuntu 22.04 only bug

I can provide more system info if you need anything specific.

**Comment by cat-master21** [comment]
This indeed happens with Kali on bash and zsh to.
