### ISSUE TITLE
cutefish-calculator-git is unable to install

### ISSUE THREAD

**Issue by Chadano** [pacstall/pacstall#573]
### Describe the bug

I installed cutefish-calculator-git via terminal with Pacstall -I and it stated that there was a dependency issue and gave an error.

### To reproduce

pacstall -I cutefish-calculator-git

I believe the issue could be due to the fact that cutefish-core-git has not been installed yet.

### Expected behavior

The package installs

### Screenshots

![image](https://user-images.githubusercontent.com/90976178/163710645-b2480013-a348-417e-a97c-c3aed8147545.png)

### OS version

Ubuntu 21.10

### Pacstall version

1.7.3

**Comment by Henryws** [comment]
Try installing fishui-git
