### ISSUE TITLE
Link Broke

### ISSUE THREAD

**Issue by AlejandroRodriguezA** [pacstall/pacstall#578]
Is a small issue...

On the page https://github.com/pacstall/pacstall/wiki/How-to-contribute, the link: [how Pacscripts work](https://github.com/pacstall/pacstall-programs/blob/master/make-a-pacscript.md#creating-a-pacscript) is no working

![Screen Shot 2022-04-27 at 11 32 40 PM](https://user-images.githubusercontent.com/58140306/165634772-aa06183a-ff94-4d45-b9d8-5515cf6cfc75.png)
.

**Comment by Henryws** [comment]
https://github.com/pacstall/pacstall/wiki/Pacscript-101

Here's the proper link

**Comment by Henryws** [comment]
And fixed!
