### ISSUE TITLE
pacstall - Alias for apt update && apt upgrade

### ISSUE THREAD

**Issue by Heus-Sueh** [pacstall/pacstall#605]
### Is your feature related to a problem? Please describe.

.

### A clear and concise description of what you want to happen.

only the command 'pacstall' for upgrade the system
like paru of arch linux

### Additional context

I think it would make the user's life easier

**Comment by Heus-Sueh** [comment]
![Screenshot_20220619-183514_GitHub_1.png](https://user-images.githubusercontent.com/98482469/174501562-d8ab03c8-1638-4c2c-8644-066027f5cb7a.png)
![Screenshot_20220619-183459_GitHub_1.png](https://user-images.githubusercontent.com/98482469/174501569-530571de-3099-4da9-93c1-fee15419ab4b.png)

**Comment by RayJW** [comment]
I think you might be searching for something like [Topgrade](https://github.com/r-darwish/topgrade). I'm not sure if the Teams' goal is to create a complete software update utility.

**Comment by Henryws** [comment]
Pacstall is integrated into Topgrade.

**Comment by Henryws** [comment]
We have a caching of pacscripts system, just not a build cache

**Comment by D-Brox** [comment]
Yes, have a cache of the packages installed, but not of the installable packages.

**Comment by Henryws** [comment]
We'll consider this during the Rust rewrite.
