### ISSUE TITLE
Drop support of deb packages in favor of deb-get

### ISSUE THREAD

**Issue by natanjunges** [pacstall/pacstall#624]
### Is your feature related to a problem? Please describe.

Both projects offer ways to install third-party `deb` packages and update them, but [`deb-get`](https://github.com/wimpysworld/deb-get) is more focused in that and has better version control (the scripts do not have to be updated every time a new version is available).

### A clear and concise description of what you want to happen.

The `deb` packages would be removed from the `pacstall` repository, but they would be ported to [`deb-get`](https://github.com/wimpysworld/deb-get). Both projects could recommend each other, and even become interoperable in the future.

### Additional context

A discussion was started [here](https://github.com/wimpysworld/deb-get/issues/94).

**Comment by Henryws** [comment]
> better version control
> the scripts do not have to be updated every time a new version is available

Those seem to be opposites.

**Comment by natanjunges** [comment]
What I mean is that new versions are automatically detected, besides offering support for different architectures.

**Comment by Henryws** [comment]
It seems that packages are hardcoded into deb-apt. Why?

**Comment by natanjunges** [comment]
The list of supported software is rather small, and it is simpler to not require any extra downloads. But there is support for custom user includes now, and a separate repository approach could be implemented as the list of software grows.

**Comment by Henryws** [comment]
What about hash verification?

**Comment by natanjunges** [comment]
The packages are all downloaded using HTTPS, so it is mostly redundant.

**Comment by Henryws** [comment]
Hash verification != Https


What if a package is corrupted on download? Doesn't matter if it's https.

**Comment by Henryws** [comment]
> In such cases, it might indeed be useful to have some form of verification. Can you open an issue suggesting that?

No, I don't use deb-get.

**Comment by natanjunges** [comment]
OK, then I can open one myself.

**Comment by Henryws** [comment]
I'm going to close this issue because we're **not** removing a core feature of pacstall that we have supported for over a year, in favor of a project that started 3 months ago.
