### ISSUE TITLE
Verify the `pacstall.dev` URL on GitHub

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#64]
**Is your feature request related to a problem? Please describe.**
Verify the `https://pacstall.dev` URL

**Describe the solution you'd like**
Verify it using the steps [here](https://github.com/orgs/pacstall/domain/156396/verification_steps)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Henryws** [comment]
I tried, but it didn't work. I'll keep trying though!

**Comment by Henryws** [comment]
It's not working, and it's not really a huge problem so I'll close this
