### ISSUE TITLE
Change Spinner

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#68]
**Is your feature request related to a problem? Please describe.**
The current spinner is very basic, and looks bad, I propose we change it

**Describe the solution you'd like**
Use this braille spinner set
```
    spinners=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
```

I have come up with a spinner function here (with the help of [this](https://gist.github.com/damekr/d6e26dfa61787bb2aea0e8771dc2f1e9))
```bash
#!/bin/bash
spin()
{
    spinners=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
    msg=$1
    fg="\e[34m"
    reset_color="\e[0m"

    # hide cursor
    tput civis

    while true
    do
        for spinner in "${spinners[@]}"
        do
            sleep 0.05
            printf " $fg$spinner$reset_color \e[1m$msg\r" 2>/dev/null
        done
    done

    # show cursor
    tput cnorm || true
}

spin "Updating something"
```
I would like this to get incorporated into pacstall (maybe modify the function to suite the needs)

**Describe alternatives you've considered**
None

**Additional context**
A static screenshot of the spinner
![ss](https://0x0.st/-Lax.png)

**Comment by wizard-28** [comment]
Don't implement this in v1.4, we should do this one in v1.5 (I am thinking of a UI overhaul for that release)

**Comment by Henryws** [comment]
I tried braille, but it messed up on my screen. I'll try it though

**Comment by wizard-28** [comment]
Try the code I wrote as a sample above, see if that works

**Comment by Henryws** [comment]
Nevermind, it works! And it looks amazing!

**Comment by Henryws** [comment]
Although I would prefer the spinner to be at the end of the line

**Comment by Henryws** [comment]
Just noticed, you need to remove `tput civis` at the end because it still keeps the cursor hidden

**Comment by wizard-28** [comment]
> Although I would prefer the spinner to be at the end of the line

I prefer it inline with the text (The AUR helpers and other CLI tools do it inline (like `hyperfine`))

**Comment by Henryws** [comment]
And the spinner is supposed to be called with an `&`, like [here](https://github.com/pacstall/pacstall/blob/79c31337b09540676e89b795a79f9db5176877e1/misc/scripts/upgrade.sh#L44).

Like this:
```bash
codeToCheckForUpdates &
spin "Searching for updates"
```

**Comment by Henryws** [comment]
And as a side note, for the persistent updates, if someone was maintaining a fork, couldn't they change the references to the update code so they update once, and then they can update on that fork with `sudo pacstall -U` until they specifically use `sudo pacstall -U name branch`

**Comment by wizard-28** [comment]
Don't write side notes in here, DM me in discord or open a new issue, this thread should be clean.

Destructing the last 2 comments in 10 secs.

**Comment by Henryws** [comment]
Yeah, I'm having trouble trying to make this work with pacstall, will keep trying though

**Comment by wizard-28** [comment]
> Yeah, I'm having trouble trying to make this work with pacstall, will keep trying though

Don't try it now, this is a part of v1.5, let's finish and v1.4 first.

**Comment by Henryws** [comment]
> > Yeah, I'm having trouble trying to make this work with pacstall, will keep trying though
> 
> Don't try it now, this is a part of v1.5, let's finish and v1.4 first.

I know it's in 1.5, but getting it to work early is better than late

**Comment by NarutoXY** [comment]
https://unix.stackexchange.com/questions/225179/display-spinner-while-waiting-for-some-process-to-finish

According to one comment, we can animate the spinner like the one proposed by @wizard-28.

**Comment by Henryws** [comment]
That’s actually the code for the current spinner
