### ISSUE TITLE
Installing item with multiple repositories, dependencies defaults to default repo

### ISSUE THREAD

**Issue by ajstrongdev** [pacstall/pacstall#680]
### Describe the bug

Installing the `linux-kernel` package from https://github.com/rhino-linux/repo has dependencies default to the default Pacstall repository, which is a patch behind. Therefore it's installing the 6.0 Linux kernel instead of 6.0.1

### To reproduce

Add the Rhino Linux repository: `pacstall -A https://raw.githubusercontent.com/rhino-linux/repo/master`

Install linux-kernel `pacstall -I linux-kernel`

Choose to install via rhino-linux/repo

### Expected behavior

Installs dependencies via `rhino-linux` repository

### Screenshots

![image](https://user-images.githubusercontent.com/90976178/196714027-623aaa4c-2960-4836-84ae-35d8497c3ea0.png)

### OS version

Ubuntu 22.04

### Pacstall version

2.0.1 Mellow

**Comment by Henryws** [comment]
Ok we should probably add a check for what the latest version in all repos is, or, make pacdeps install from the same repository the base package is

**Comment by httpllamaz** [comment]
The second options seems best to me.

**Comment by Henryws** [comment]
@wizard-28 thoughts on this?

**Comment by Henryws** [comment]
Just to confirm, does this also happen on `3.0.0`?

**Comment by wizard-28** [comment]
> @wizard-28 thoughts on this?

Second option is better, as pacdeps from the same repository are likely to be tested to work with the package.

**Comment by httpllamaz** [comment]
> Just to confirm, does this also happen on `3.0.0`?

Remind me to test tomorrow

**Comment by Henryws** [comment]
> > Just to confirm, does this also happen on `3.0.0`?
> 
> Remind me to test tomorrow

Yo.
