### ISSUE TITLE
pacstall -U pacstall master does not upgrade to 3.0.1

### ISSUE THREAD

**Issue by httpllamaz** [pacstall/pacstall#688]
### Describe the bug

pacstall -U pacstall master does not upgrade to the latest version. A hotfix was released 3 hours ago and updating Pacstall does not fix it.

### To reproduce

pacstall -U pacstall master

### Expected behavior

Upgrades to 3.0.1

### Screenshots

N/A

### OS version

Ubuntu 22.04

### Pacstall version

3.0.0

**Comment by Henryws** [comment]
fixed.

**Comment by httpllamaz** [comment]
LGTM, works as intended now.
