### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by soumyatheman** [pacstall/pacstall#689]
Why is it necessary to name a package that's installed from a deb file as pkgname-deb? Why can't it just be pkgname?

**Comment by Henryws** [comment]
So that pacstall can tell that it should install a deb.

**Comment by Henryws** [comment]
You mean you want an example on how to make a pacscript for a package that is primarily distributed by flatpak?

**Comment by soumyatheman** [comment]
exactly, because a lot of cases, build methods are also not mentioned by the devs

**Comment by Henryws** [comment]
Ok I can try later today.

**Comment by Henryws** [comment]
I won't be maintaining this btw. This is just for an example that you asked for.

**Comment by soumyatheman** [comment]
Okay lemme check that out

**Comment by soumyatheman** [comment]
I need a particular tag to be cloned, How should I type the url then?

**Comment by Henryws** [comment]
```
git fetch --unshallow
git checkout tag
```

**Comment by soumyatheman** [comment]
> ```
> git fetch --unshallow
> git checkout tag
> ```

I should write these in the prepare function? Right?

**Comment by Henryws** [comment]
Yes

Sent from Proton Mail mobile

-------- Mensaje original --------

**Comment by soumyatheman** [comment]
BTW I have one pacscript ready, this is of a deb. Please check this out, also if possible test this :-)

**Comment by Henryws** [comment]
Create a PR for that package 😊

**Comment by soumyatheman** [comment]
> 

This is not working. I'm not understanding the way.. Can you please help me understanding how to use that

**Comment by Henryws** [comment]
How to use what?

**Comment by soumyatheman** [comment]
Lemme explain you. I'm trying to make a pacscript for [g4music](https://gitlab.gnome.org/neithern/g4music). Now I can get the source-code via tar.gz or tar.xz or zip files. What should I do after that? Should I write some code to extract that? Or pacstall will automatically extract that? Also, can you give a pacscript of that g4music if you can? I'll maintain it thereafter.

**Comment by Henryws** [comment]
No, pacstall automatically extracts files. I'm also making a pacscript for G4music, so maybe we could compare scripts and choose a single one to add to the repo.

**Comment by soumyatheman** [comment]
No if you're making it, then I must wait, learn from your one and make pacscript for another software called paper.

**Comment by soumyatheman** [comment]
Did you make one pacscript for G4music?

**Comment by Henryws** [comment]
I'm at school. I'll try when I'm home.

**Comment by soumyatheman** [comment]
please check this pacscript

name="g4music"
gives="g4music"
version="1.8.2"
url="https://gitlab.gnome.org/neithern/g4music/-/archive/v${version}/g4music-v${version}.tar.gz"
repology=("project: g4music")
description="Play your music in an elegant way"
hash="3b7d2f47a08b6ce9a2bebf2ce0e4295aa07499628f18571483d809ca9270ab94"
maintainer="সৌম্যদীপ <soumyadeepghosh2004@zohomail.in>"
build(){
meson setup build --buildtype=release
}

**Comment by Henryws** [comment]
Make a PR then.

**Comment by soumyatheman** [comment]
Please check this, I don't know how to make pacscripts from this type of tars, it's actually not installing anything in my machineSent using Zoho Mail ---- On Wed, 07 Dec 2022 23:35:48 +0530  ***@***.***  wrote ----
Make a PR then.

**Comment by Henryws** [comment]
What error do you get?

**Comment by wizard-28** [comment]
@soumyatheman Can you join our chat servers like Discord or Matrix instead of commenting on this issue? This leads to unnecessary spam.

**Comment by soumyatheman** [comment]
Everything works fine, also the dpkg works well, but nothing actually installs. Even after dpkg shows g4music i installed, no such app is installedSent using Zoho Mail ---- On Wed, 07 Dec 2022 23:47:15 +0530  ***@***.***  wrote ----
What error do you get?

**Comment by soumyatheman** [comment]
I actually want, what's the link of discord?Sent using Zoho Mail ---- On Wed, 07 Dec 2022 23:49:46 +0530  ***@***.***  wrote ----
@soumyatheman Can you join our chat servers like Discord or Matrix instead of commenting on this issue? This leads to unnecessary spam.
