### ISSUE TITLE
consider new approach to managing privileges, preferring root invocation

### ISSUE THREAD

**Issue by brainchild0** [pacstall/pacstall#691]
# Problem

I have noticed a particular design pattern common for AUR helpers, which appears also to have been adopted by the Pacstall utility.

The utility prefers to run as the regular user, and during its operation acquire permissions for elevated privileges, to be utilized when the built packages are ready for installation. 

The approach carries several limitations, including the following:

- The build work is performed and saved under the user directory, even though it has system-wide scope. Users may not want the work saved in their own space, and may benefit from invoking operations that share artifacts with operations invoked by other users.
- Users are accustomed to invoking package management tools with elevated privileges, and may include such invocations within operations already carrying  such privileges. 

# Proposal

An alternative approach would be the creation of a special user for Pacstall work operations, which carries file permissions to a designated system directory. The utility then may delegate work operations to a worker process with the reduced priviliges of this special user, and then, when the process completes, proceed with package installation.

Inverting the point at which privileges are changed, and in which direction, may  represent overall a design that is more elegant and better integrated.

# Notes

I have recently received my first exposure to Arch-family operating systems, and only a short time after learning about AUR, and wondering why the concept has not been adopted in other Linux families, came to learn of the Pacstall project. I am happy about this work, since I have been a long-time user of Ubuntu, and more recently Linux Mint, and have negotiated all the obstacles related to package management familiar to so many.

**Comment by Henryws** [comment]
I'm gonna be frank, I don't understand what you're saying. Can you say it in less wordy terms?

**Comment by wizard-28** [comment]
We've already been planning this for the Python/Rust rewrite of Pacstall. Thanks for creating this issue.

---

> The build work is performed and saved under the user directory, even though it has system-wide scope. Users may not want the work saved in their own space, and may benefit from invoking operations that share artifacts with operations invoked by other users.

The build work is performed at `/tmp/pacstall` at the moment.

**Comment by brainchild0** [comment]
> So basically, using a special `pacstall` user or using `fakeroot` (which we tried before).

Yes, but also enforce the root check immediately, the same as for `apt-get` or `dpkg`, instead of requesting elevated privileges interactively. It is better for consistency of user experience and for clarity and reliability in automated wrappers.

DKMS builds may be executed as root, however, they probably entail a smaller set of security concerns by being limited in the variety of sources.

**Comment by brainchild0** [comment]
> I'm gonna be frank, I don't understand what you're saying. Can you say it in less wordy terms? Do you mean to say we should wrap everything in sudo?

Are the summaries given by others helpful?

**Comment by Henryws** [comment]
Yes, we have discussed on our discord dev chat and I know what you mean now.

**Comment by Henryws** [comment]
Also the reason why AUR helpers run as a normal user is because `makepkg` refuses to run as root.

**Comment by brainchild0** [comment]
Ultimately it's not relevant though, because a wrapper running with elevated privileges may invoke a child without them.

**Comment by Henryws** [comment]
All an AUR helper does at its core is run the command `makepkg`. None of an AUR helpers functions really *require* elevated privileges.

**Comment by brainchild0** [comment]
When I run `yay -S <pkgname>`, then the package is installed, as long as the build succeeds. I believe the process installs the package at the end, which is why it prompts for a password at the beginning.

**Comment by Henryws** [comment]
Yes, it is running a sudo loop in the background so that you do not have to re-enter your password on super long builds.

**Comment by brainchild0** [comment]
Even then it would be better to open a root shell, and then send the commands through a pipe.

**Comment by brainchild0** [comment]
> The build work is performed at `/tmp/pacstall` at the moment.

Thanks for the correction. I think the AUR helpers I have encountered have used the home dir.
