### ISSUE TITLE
request for interface specific for new package requests

### ISSUE THREAD

**Issue by brainchild0** [pacstall/pacstall#692]
#  Problem

The project web site lists packages currently maintained, but offers no means for regular users to submit requests for packages they wish to be included, or for potential package maintainers to discover projects of wide interest.

# Request

Requested is an interface through which users may submit and upvote package requests.

# Alternatives

The issue tracker is not an optimal platform for requesting packages, because maintenance of the tool chain is orthogonal to its use by package maintainers.

**Comment by Henryws** [comment]
> but offers no means for regular users to submit requests for packages

That happens on GitHub. As for requesting packages, go to our website, search for something that doesn't exist. You'll see a link to a templated URL for a package request.

**Comment by brainchild0** [comment]
Is there a tag for marking issues specifically relating to package requests? If so, it may be helpful to place a link for a search query directly on the main web site. I feel it would be beneficial to emphasize access to package requests with at least a slightly cleaner separation from design issues and bug tracking.

**Comment by Henryws** [comment]
![IMG_1594](https://user-images.githubusercontent.com/58742515/198117917-803c4d79-18f6-4765-9b5f-fb5ebc0700d1.jpeg)

We have that.

**Comment by Henryws** [comment]
> 

Yes, we have a tag for package requests. [Here’s a list](https://github.com/pacstall/pacstall-programs/issues?q=is%3Aissue+is%3Aopen+label%3A%22package+request%22).

**Comment by brainchild0** [comment]
Thank you. I had not noticed it on the main web site. It may be helpful to add the same link you just provided to the web site, if it is not  already provided.

**Comment by Henryws** [comment]
It already exists on the site, just in the form of a github issue you can fill out, not a list of requested packages already requested.

**Comment by brainchild0** [comment]
I understand. Then my only remaining suggestion is to consider adding the link.
