### ISSUE TITLE
support distribution differences through metadata or conditional evaluation

### ISSUE THREAD

**Issue by brainchild0** [pacstall/pacstall#698]
# Problem

The Wiki provides the following explanation:

> Pacstall is intended for use on Ubuntu based distributions, however most packages in our repository work on Debian. A couple Pacscripts may not work as they might have outdated dependencies or a dependency name change, but for the most part, Pacstall does work fine on Debian.

That is, build scripts are targeted for Ubuntu systems, and it remains a matter for chance whether any may work under  vanilla Debian.

# Request

Two successive stages of development may be considered to provide better support multiple distributions, as follows:

1. Declarations in the build script to designate the distributions for which a script may be considered explicitly to support (or explicitly not to support).
2. Conditional evaluation of script values, to provide support for multiple distributions, despite differences, in the same build script.

Note that for some purposes   releases, of a distribution, not just the overall project, are useful distinctions.

Also note that some derived distributions, such as Linux Mint, are designated by an Ubuntu base release as well as an LM release.

# Notes

The proposal given appears to be the most general to support all Debian-based, or APT-based, operating systems,  through a unified build system, without regressing current functionality or level of support.

**Comment by Henryws** [comment]
We already have a method of declaring which versions to not support [like so](https://github.com/pacstall/pacstall-programs/blob/08c4afeb940f56de2780c4a4f6baa947e6e5a881/packages/shellharden/shellharden.pacscript).

We also have a method for declaring different packages per distro [like so](https://github.com/pacstall/pacstall-programs/blob/8340f9d423b4c410abae454fb7e204d6834c8ff2/packages/tenacity-git/tenacity-git.pacscript).

**Comment by brainchild0** [comment]
Perhaps it is a documentation and policy issue only. The documentation reports that some packages may work in vanilla Debian, and some not, without any assurances.

**Comment by brainchild0** [comment]
However, it would be helpful to add functionality in the tool that populates certain values in advance. I notice one script reads the files in `/etc` directly. It would be cleaner if the logic for resolving such data were standardized and made internal to the tool, such that the script may simply use the pre-populated values. If this logic appears in the build scripts, then they are vulnerable to breakage, which is hard to fix, because it is spread across the different scripts.

**Comment by Henryws** [comment]
So you mean something like, `exclude_distros=('debian:stable' 'ubuntu:lts')`?

**Comment by brainchild0** [comment]
I suppose there are two issues. One is how selection criteria are expressed in the scripts. The other is how the complicated, vulnerable, and unstable logic may be maintained internally to the tool, allowing scripts to be simple but robust.

**Comment by wizard-28** [comment]
> So you mean something like:
> 
> ```shell
> exclude_distros=(
> 	'debian:stable'
> 	'debian:stretch'
> 	'ubuntu:lts'
> 	'ubuntu:17.04'
> )
> ```

Why don't we just use `incompatible` array from the PACBUILD spec here?

```bash
incompatible=('debian::jessy' 'ubuntu::20.04')
```

---

> Of course we'd need someway to retrieve the LTS status, along with debian version names, or we could drop them in favor of straight numbers.

I think it's better to just version numbers

**Comment by brainchild0** [comment]
> > Of course we'd need someway to retrieve the LTS status, along with debian version names, or we could drop them in favor of straight numbers.
> 
> I think it's better to just version numbers

If you are populating values accessible by the script, I would suggest including the release names, because sometimes they are needed by the build logic.

**Comment by wizard-28** [comment]
> > > Of course we'd need someway to retrieve the LTS status, along with debian version names, or we could drop them in favor of straight numbers.
> > 
> > 
> > I think it's better to just version numbers
> 
> If you are populating values accessible by the script, I would suggest including the release names, because sometimes they are needed by the build logic.

Examples?

**Comment by brainchild0** [comment]
Examples... of Pacstall build scripts, or projects with complicated build logic that might these fields?

**Comment by wizard-28** [comment]
> Examples... of Pacstall build scripts, or projects with complicated build logic that might these fields?

Both ideally. Just for future reference in this issue.

**Comment by brainchild0** [comment]
> > Examples... of Pacstall build scripts, or projects with complicated build logic that might these fields?
> 
> Both ideally. Just for future reference in this issue.

I have no particular experience with Pacstall scripts. 

I have definitely seen very ugly logic in build scripts. For example, in some instances, a web resource will be downloaded, and the name will be derived by interpolating a distribution release name. If I find a reference to an actual project then I will share it. I am not thinking of any specific one at the moment.

In any case, relying on release name is a common pattern, so I definitely advise against assuming that a version number is sufficient.
