### ISSUE TITLE
Pacstall proposes to update already up-to-date package (fixed version)

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#704]
### Describe the bug

For package `obs-backgroundremoval-git`, the latest commit in github is not buildable, so the version was fixed manually in the pacscript.
Now everytime doing pacstall updates, it proposes to update the package again, to install the same version.

### To reproduce

1. pacstall -I `obs-backgroundremoval-git`
2. pacstall -Up
3. pacstall -Up

### Expected behavior

Does not propose to update to the same version

### Screenshots

![image](https://user-images.githubusercontent.com/10415894/198870556-5aa671e0-7647-4927-8f59-416af17b7084.png)

### OS version

Kubuntu 22.10

### Pacstall version

3.0.1, master branch

**Comment by Zahrun** [comment]
I'm ok to do that, but may I first ask if it would not make more sense that pacstall considers `"${version}"` to check a version number? Only if `version=$(pkgver)`, use that value?

**Comment by Henryws** [comment]
`versión` is the canonical variable. It must be given some form of input, such as a string, or the output of a function. It can be anything as long as it is supplied. The internal `version=$(pkgver)` is to prevent that extra line in scripts.
