### ISSUE TITLE
automation of http downloading of debian-style packages

### ISSUE THREAD

**Issue by brainchild0** [pacstall/pacstall#710]
### Is your feature related to a problem? Please describe.

Some projects maintain downloadable package files, which support automated install through the package manager, but not automated updates.

### A clear and concise description of what you want to happen.

What support is currently available for using Pacstall to automate  obtaining updates   for applications published as Debian packages through a web request, but not available from a signed Debian repository?

**Comment by Henryws** [comment]
You mean like `pacstall -I https://foobar.com/foo.deb`?

**Comment by brainchild0** [comment]
Not quite, sorry, my explanation was quite weak.

I was trying to explain the idea of a build script not actually generating a package, but instead simply pointing to an existing one published as a basic web resource.  When the web resource is updated, the build script would fetch the new version of the resource and perform the install.

**Comment by Henryws** [comment]
Can you give an example?

**Comment by brainchild0** [comment]
Do you mean give an example of an actual application that is published in such a way? It is really quite common.

**Comment by Henryws** [comment]
Sure.

**Comment by brainchild0** [comment]
MarkText would be an example of an application that is [released](https://github.com/marktext/marktext/releases) through Debian-style packages not published in a formal repository.

**Comment by brainchild0** [comment]
MarkText would be an example of an application that is [released](https://github.com/marktext/marktext/releases) through Debian-style packages not published in a formal repository.

**Comment by Henryws** [comment]
Sorry but I'm still confused.

**Comment by brainchild0** [comment]
For some software projects,   the author publishes a package in the form of a `.deb` file, which  a user may download through a web browser, and then install on the local system. This scheme has no    automation for upgrades. Upgrading to a new version requires manually checking the web site for a new file to download. However, it easier for the project author than maintaining a Debian repository or Launchpad site.

The common case for a Pacstall build script is downloading source code to the local system, building the binary targets, and then creating a `.deb` package.

In the case that the project author builds the binaries and publishes a `.deb`, the user may remain   upgraded to the latest version,   if  installing a target package through Pacstall involved  simply *downloading an existing `.deb` package   from a web server*, and  simply installing it to the system.

Is such a case supported as a possible build script?

**Comment by Henryws** [comment]
You mean `-deb` pacscripts?

[Example](https://github.com/pacstall/pacstall-programs/blob/master/packages/anydesk-deb/anydesk-deb.pacscript).

**Comment by brainchild0** [comment]
Yes, that is the idea I was describing.

**Comment by Henryws** [comment]
So does this answer your initial question?

**Comment by Henryws** [comment]
So does this answer your initial question?

**Comment by brainchild0** [comment]
Yes, but I am wondering, does your earlier comment suggest that scripts following the form I described should have, by convention, a name ending in `-pac`?

**Comment by Henryws** [comment]
> Yes, but I am wondering, does your earlier comment suggest that scripts following the form I described should have, by convention, a name ending in `-pac`?

No, pacscripts should **never** not be in a repo for production.

**Comment by brainchild0** [comment]
Sorry, I asked about the convention for naming packages. I am not understanding your answer.

**Comment by Henryws** [comment]
You mean like a pacscript file in a GitHub release for example?

**Comment by brainchild0** [comment]
Your remarked...

> You mean `-deb` pacscripts?

I later wrote, referring to that remark...

> does your earlier comment suggest that scripts following the form I described should have, by convention, a name ending in `-pac`?

However, it appears I made an error, and should have written...

> does your earlier comment suggest that scripts following the form I described should have, by convention, a name ending in *`-deb`*?

In other words, did you use the string `-deb` to suggest that the package name should end in with that postfix?

**Comment by Henryws** [comment]
I’m so sorry that I’m not understanding you.

https://libreddit.spike.codes/r/pacstall/comments/pfmahd/download_binaries_instead_of_building_from_the/

If you look at the comments, you will see how we determine what suffix a package must be named based on the type of download.

Thank you for being patient with me 😓

**Comment by brainchild0** [comment]
I understand, based on the article. 

You are using a convention for the package names, to express the  general approach that the package is generated from the script.

For me, it is easier as a user if the package name is simply the application, without the suffix. In my view, it is the job of the package maintainer to choose the best way to generate the package, without changing the name that is exposed to the user.
