### ISSUE TITLE
bug: `name shows wrong of a package in the pacstall website`

### ISSUE THREAD

**Issue by soumyatheman** [pacstall/pacstall#724]
### Describe the bug

The name of a package is linked-deb, but when I enter into the details page of that package, it shows linked-bin, which is supposed to be for the binary file packages.

### To reproduce

1. go to pacstall.dev
2. search `linked-deb`
3. open the package details

### Expected behavior

It should've shown the name as linked-deb

### Screenshots

![Screenshot from 2022-12-05 08-25-29](https://user-images.githubusercontent.com/72045785/205539776-f2ad14d1-8dec-41c5-8ad0-5618421c8337.png)

### OS version

any

### Pacstall version

latest

**Comment by Henryws** [comment]
We are aware of the problem, and are working on it.

**Comment by soumyatheman** [comment]
Thank you
