### ISSUE TITLE
bug: Runtime dependencies are not installed before building

### ISSUE THREAD

**Issue by soumyaDghosh** [pacstall/pacstall#727]
### Describe the bug

Meson packages check the runtime packages before compiling the package. But pacstall doesn't install the packages before compiling it

### To reproduce

Install this meson package:

```bash
name="g4music"
gives="g4music"
version="1.8.1"
build_depends="meson valac"
depends="libgtk-4-dev libgstreamer1.0-dev libadwaita-1-dev"
url="https://gitlab.gnome.org/neithern/g4music/-/archive/v${version}/g4music-v${version}.tar.gz"
repology=("project: g4music")
description="Play your music in an elegant way"
maintainer="সৌম্যদীপ <soumyadeepghosh2004@zohomail.in>"

prepare() {
  true
}

build(){
	meson setup build --buildtype=release
}

install(){
	sudo meson install -C build --destdir=${pkgdir}
}
```

### Expected behavior

All the deps should have been installed properly

### Screenshots

NA

### OS version

Ubuntu 22.10

### Pacstall version

3.0.2

**Comment by Henryws** [comment]
This can be fixed by adding the dependency to both `depends` and `build_depends`.
