### ISSUE TITLE
`removescipt`, `postinst` need to be run as root

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#73]
**Describe the bug**
Title

**To Reproduce**

1. Remove a pacscript with the `removescript` function
2. See error

**Expected behavior**
No errors

**Screenshots**
![img](https://0x0.st/-LIg.png)

**Desktop (please complete the following information):**

- OS + version: Pop 20.04
- Pacstall Version + branch: 1.3 develop

**Additional context**
None

**Comment by Henryws** [comment]
removescript and postinst should have sudo in the functions itself, the function doesn't need to be run with root, just the commands inside. Just like manually putting in the commands

**Comment by wizard-28** [comment]
As a sidenote, in 1.5, we ARE moving every command to a separate file, no writing the commands in the main script `/bin/pacstall`, as this creates lot of issues, like the onces faced in this issue (If the remove command was a separate file, a simple `sudo /usr/share/pacstall/scripts/removescript.sh` would work)

**Comment by Henryws** [comment]
it would be in `/usr/share/pacstall/scripts/remove.sh` instead

**Comment by wizard-28** [comment]
> removescript and postinst should have sudo in the functions itself, the function doesn't need to be run with root, just the commands inside. Just like manually putting in the commands

Give a reason, why most of the stuff that people do in removescript requires root, so it makes sense to run it with root instead of doing sudo for every command

**Comment by Henryws** [comment]
Because that's how it would manually be done

**Comment by Henryws** [comment]
you don't run `sudo su` then run post install commands

**Comment by wizard-28** [comment]
But it adds redundancy, doing sudo for every command.

I think we should should deviate from the manual way, and have root privileges in the removescript, and postinst.

Plus the syntax would be more closer to the AUR PKGBUILD syntax, so it will be easier for people to port the packages

**Comment by wizard-28** [comment]
Plus then after #72 was merged, every pacscript using removescript is actually broken

**Comment by Henryws** [comment]
You can't run functions with sudo:
```bash
function1() {
echo "$USER"
}
henry@twilight ~ % ››› function1
henry
henry@twilight ~ % ››› sudo function1
[sudo] password for henry:
sudo: function1: command not found
henry@twilight ~ % ›››
```

**Comment by wizard-28** [comment]
I know, thats why I proposed it to be in a separate file

**Comment by wizard-28** [comment]
So we can sudo it

**Comment by wizard-28** [comment]
Or leave, now that I think about it giving granular permission control to the maintainer is a better idea
