### ISSUE TITLE
[FR] Remove packages that are already in Debian testing/Ubuntu

### ISSUE THREAD

**Issue by werdahias** [pacstall/pacstall#743]
### Is your feature related to a problem? Please describe.

-

### A clear and concise description of what you want to happen.

[alacritty](https://tracker.debian.org/pkg/rust-alacritty) and bat (cat clone) for instance are already in debian testing and ubuntu. I'd suggest to check if a package got recently added into debian unstable/testing (and ubuntu, subsequently) and then add a banner/indicator that is already in the native repos. I don't mean to to diminish the work all the voluntary pacstall devs do, but at the end of the day native packages are always better imho. Also, this could lead to (possible) conflicts when updating.
Another benefit would be to only show packages not in debian/ubuntu so duplicate installs can be avoided and official maintainers can take inspiration from there.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by Henryws** [comment]
We are not going to remove a package unless the maintainer of said package agrees.

**Comment by werdahias** [comment]
removing might be a bit harsh. imho if a package gets accepted into the official repositories then the pacstall maintainer doesn't need to maintain it anymore (unless they want). Focusing on packages that aren't in debian/ubuntu yet would draw more users to use it; it's also what made the AUR so big.
As a maintainer myself I'd hate for someone to put in all this effort to provide a deb if one week later an native package gets uploaded.

**Comment by Henryws** [comment]
Generally packages are added because users want faster updates for them, or maybe they want to compile them with their own features. I would not, however, merge a package that is just downloading the deb from some repo, unless it is needed for a specific reason (which has happened a couple times).

**Comment by werdahias** [comment]
adding at least an informational tag if a package is available in the official repos would be good measure imho. For instance pipes.sh-bin could receive this one. And if it's orphaned (like in this case) I'd ping the pacstall maintainer and remove it if I wouldn't hear back for three months.

**Comment by Henryws** [comment]
What if a package was compiled in the official repos without certain features? Should we show a banner saying that the "same" package is also in the repos? I feel like it would be obnoxious.

**Comment by werdahias** [comment]
While I agree that this a possible issue, it's a rare edgecase. Some packages don't have compile-time features.  Like I said, I wouldn't want someone to put in all the effort for a pacscript to then have a official package anyway a few weeks later. Official packages are also signed and reviewed at least two times.

**Comment by Henryws** [comment]
It doesn't take much effort to create a Pacscript though. Our goal is to make packaging as easy as possible. We also review Pacscripts before merging to ensure they are up to our standards.

**Comment by werdahias** [comment]
You don't have to add the informational tag if you don't want to, imho this would be better because of aforementioned reasons.

**Comment by werdahias** [comment]
and the examples I listed all ship just one binary file + manpage which isn't any different from debian
