### ISSUE TITLE
Pacstall fails to install a package

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#749]
### Describe the bug

Pacstall fails to install a package

### To reproduce

`pacstall -I yabridge`

### Expected behavior

Pacstall installs package

### Screenshots

[log.log](https://github.com/pacstall/pacstall/files/10307139/log.log)

### OS version

Kubuntu 22.10

### Pacstall version

3.1.0, master branch

**Comment by Henryws** [comment]
Run `pacstall -U pacstall master` and try again.

**Comment by Henryws** [comment]
Run `pacstall -U pacstall master` and try again.

**Comment by Henryws** [comment]
Fixed in release #752

**Comment by Zahrun** [comment]
It works, thanks
