### ISSUE TITLE
`-U` flag not working without `sudo`

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#75]
**Describe the bug**
Currently we can't update pacstall (`/usr/bin/pacstall`) without `sudo`

**To Reproduce**
NA

**Expected behavior**
Obvious

**Screenshots**
NA

**Desktop (please complete the following information):**

- OS + version: Pop!_OS 20.04
- Pacstall Version + branch: 1.3 develop

**Additional context**
None

**Comment by Henryws** [comment]
In the -U flag, all downloading is run with sudo, I don't know why it wouldn't work

**Comment by wizard-28** [comment]
I tried multiple times to update to the `bugfix/quiet-R` branch, but it didn't update the `/bin` file.

When I tried with `sudo` it worked, Can you try updating without `sudo` to some other branch to test this?

**Comment by Henryws** [comment]
It works for me

**Comment by wizard-28** [comment]
Hmm... so probably it was a me-problem. Closing this
