### ISSUE TITLE
Pacstall does not stay in the same folder between build and install anymore

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#758]
@wizard-28 
It seems latte-dock-git does not build anything anymore

**Comment by Henryws** [comment]
I've done more digging and it seems that we're not going to be able to "fix" this issue. Basically from here on out we must treat each function used as if it were starting back at the build directory.

**Comment by Zahrun** [comment]
Ok then let’s make the changes to the pacscripts 👍
