### ISSUE TITLE
optdepends in outputted debs are depends instead of Suggests when installing

### ISSUE THREAD

**Issue by cat-master21** [pacstall/pacstall#762]
### Describe the bug

When building debs with pacstall, the optdepends become Depends and not a recommends/suggests.

### To reproduce

1. run `pacstall -I -B os-installer-git` or on any pacscript with the optdepends field.
2. noticed that in outputted deb's `control`, the Depends field has the pacscript's optdepends which the package does not depend on. For this case `os-installer-git`:
```
Suggests: epiphany-browser
Depends: libgnome-desktop-4-2, libadwaita-1-0, libgweather-4-0, python3-yaml, libudisks2-0, libvte-2.91-gtk4-0, gir1.2-gnomedesktop-4.0, gir1.2-vte-3.91, gnome-disk-utility, gnome-control-center
Package: os-installer-git
Version: 42b0e2c3
Architecture: all
Section: Pacstall
Priority: optional
Maintainer: cat-master21 <96554164+cat-master21@users.noreply.github.com>
Description: A generic and changable os-installer
Installed-Size: 557	/usr/src/pacstall/os-installer-git
```

### Expected behavior

Instead of just the first pacscripts' optdepends being in a debs' `Suggests`, all of them should be under `Suggests` not one.

### Screenshots

```
Suggests: epiphany-browser
Depends: libgnome-desktop-4-2, libadwaita-1-0, libgweather-4-0, python3-yaml, libudisks2-0, libvte-2.91-gtk4-0, gir1.2-gnomedesktop-4.0, gir1.2-vte-3.91, gnome-disk-utility, gnome-control-center
Package: os-installer-git
Version: 42b0e2c3
Architecture: all
Section: Pacstall
Priority: optional
Maintainer: cat-master21 <96554164+cat-master21@users.noreply.github.com>
Description: A generic and changable os-installer
Installed-Size: 557	/usr/src/pacstall/os-installer-git
```

### OS version

Ubuntu 23.04

### Pacstall version

master

**Comment by Henryws** [comment]
Yes, because if we use `--install-recommends`, it installs all of them. The selection part of `optdepends` is so that they will be installed when the Deb is, and only those selected.

**Comment by cat-master21** [comment]
well couldn't instead of being part of `Depends` it could be moved to Suggests? and Pacstall install the optdepends the user requests?

**Comment by Henryws** [comment]
What would be nice is selectively picking Suggests instead of all or nothing.

**Comment by cat-master21** [comment]
Yeah that would be good. In that case this would be a feature request then I guess.

**Comment by Henryws** [comment]
> ### Describe the bug
> When building debs with pacstall, the optdepends become Depends and not a recommends/suggests.
> 
> ### To reproduce
> 1. run `pacstall -I -B os-installer-git` or on any pacscript with the optdepends field.
> 2. noticed that in outputted deb's `control`, the Depends field has the pacscript's optdepends which the package does not depend on. For this case `os-installer-git`:
> 
> ```
> Suggests: epiphany-browser
> Depends: libgnome-desktop-4-2, libadwaita-1-0, libgweather-4-0, python3-yaml, libudisks2-0, libvte-2.91-gtk4-0, gir1.2-gnomedesktop-4.0, gir1.2-vte-3.91, gnome-disk-utility, gnome-control-center
> Package: os-installer-git
> Version: 42b0e2c3
> Architecture: all
> Section: Pacstall
> Priority: optional
> Maintainer: cat-master21 <96554164+cat-master21@users.noreply.github.com>
> Description: A generic and changable os-installer
> Installed-Size: 557	/usr/src/pacstall/os-installer-git
> ```
> 
> ### Expected behavior
> Instead of just the first pacscripts' optdepends being in a debs' `Suggests`, all of them should be under `Suggests` not one.
> 
> ### Screenshots
> ```
> Suggests: epiphany-browser
> Depends: libgnome-desktop-4-2, libadwaita-1-0, libgweather-4-0, python3-yaml, libudisks2-0, libvte-2.91-gtk4-0, gir1.2-gnomedesktop-4.0, gir1.2-vte-3.91, gnome-disk-utility, gnome-control-center
> Package: os-installer-git
> Version: 42b0e2c3
> Architecture: all
> Section: Pacstall
> Priority: optional
> Maintainer: cat-master21 <96554164+cat-master21@users.noreply.github.com>
> Description: A generic and changable os-installer
> Installed-Size: 557	/usr/src/pacstall/os-installer-git
> ```
> 
> ### OS version
> Ubuntu 23.04
> 
> ### Pacstall version
> master

In this pacscript, what optdepends did you select?

**Comment by cat-master21** [comment]
@Henryws I selected no optdepends. Here is the control file:
```
Suggests: epiphany-browser
Depends: libgnome-desktop-4-2, libadwaita-1-0, libgweather-4-0, python3-yaml, libudisks2-0, libvte-2.91-gtk4-0, gir1.2-gnomedesktop-4.0, gir1.2-vte-3.91, gnome-disk-utility, gnome-control-center
Package: os-installer-git
Version: 42b0e2c3
Architecture: all
Section: Pacstall
Priority: optional
Maintainer: cat-master21 <96554164+cat-master21@users.noreply.github.com>
Description: A generic and changable os-installer
Installed-Size: 557	/usr/src/pacstall/os-installer-git
```
As you can see, `epiphany-browser` is in Suggests but not `gnome-control-center` this is the bug
and also the log in case:
[log.txt](https://github.com/pacstall/pacstall/files/10365416/log.txt)
And just a reminder this is still on master branch.

**Comment by Henryws** [comment]
I'll work on this tomorrow if I have time.
