### ISSUE TITLE
Add `.deb` support in pacstall

### ISSUE THREAD

**Issue by NarutoXY** [pacstall/pacstall#77]
Can we include .deb packages for some packages like Brave Nightly in Pacstall? It will help many users who don't want to just compile packages like a web browser. It will make it even more better and similar to AUR where both git and binaries are available.

**Comment by emanuelserpa** [comment]
I think pacstall could just build debs.

I'm not using Ubuntu currently, but building debs (https://linuxconfig.org/easy-way-to-create-a-debian-package-and-local-package-repository) doesn't look that hard.

**Comment by NarutoXY** [comment]
I created pull request regarding .deb support but it is conflicting due to some recent changes. https://github.com/pacstall/pacstall/pull/93
