### ISSUE TITLE
bug: `removescript() is ran before postinstall() function while reinstalling`

### ISSUE THREAD

**Issue by soumyaDghosh** [pacstall/pacstall#783]
### Describe the bug

When we reinstall a pacscript, the removescript() is ran before running the postinst() function. So, let's say there is a command that is ran in prepare() or build() or install() and is removed via removescript() function, when the pacscript will be reinstalled, the removescript() will ran, just before postinst(); but the file that got deleted, will not be reinstalled. 

### To reproduce

`````
name="frog"
gives="${name}"
version="1.2.0"
build_depends="meson python3 python3-pip leptonica-progs libadwaita-1-0 libnotify-bin libportal-dev python3-gi python3-pydbus python3-pyzbar"
# HACK: https://github.com/pacstall/pacstall/issues/727
depends="leptonica-progs libadwaita-1-0 libnotify-bin libportal-dev python3-gi python3-pydbus python3-tesserocr python3-pyzbar"
url="https://github.com/TenderOwl/Frog/archive/refs/tags/${version}.tar.gz"
repology=("project: frog-ocr")
description="Intuitive text extraction tool (OCR) for GNOME."
hash="b2445c54f7d2b064f7ccf20be4ffcf34b689ec85e64284ac9dee91ad9f128b44"
maintainer="সৌম্যদীপ <soumyadeepghosh2004@zohomail.in>"

prepare() {
	sudo pip install pytesseract
	# Fix path to appdata
	sed -i 's|/app/share/|/usr/share/|g' frog/language_manager.py
	meson build --buildtype=release --prefix=/usr
}
build() {
	ninja -C build -j"$(nproc)"
}
install() {
	sudo DESTDIR="${pkgdir}" ninja -C build install
}
postinst() {
	#HACK: https://github.com/TenderOwl/Frog/issues/70
	sed -i 's|Exec=frog|Exec=sh -c "XDG_DATA_HOME="$HOME/.local/share/" frog"|g' /usr/share/applications/com.github.tenderowl.frog.desktop
}
removescript() {
	sudo pip uninstall pytesseract
}
````````

In this pacscript, the `pip` installs `pytesseract` in the prepare function. But the removescript() removes it during reinstallation, and `pytesseract` never gets installed again.

### Expected behavior

The removescript() should have ran before the reinstallation, i.e before the prepare(), so that everything can be reinstalled clearly.

### Screenshots

![image](https://user-images.githubusercontent.com/72045785/215096504-46652389-37f8-4281-8797-49064a6046dd.png)

### OS version

Ubuntu 22.10

### Pacstall version

3.4.0

**Comment by soumyatheman** [comment]
> That is left up to apt, not something we can really do. I think you want `preinstall()`.
Is the removescript() is ran before postinst by apt? Then I guess, we need to make sure that everything gets reinstalled, what's removed in removescript.

**Comment by Henryws** [comment]
When you reinstall, it runs removescript.

**Comment by soumyatheman** [comment]
> When you reinstall, it runs removescript.

Then what can be the fix?

**Comment by Henryws** [comment]
No fix that I know of. We could add `preinstall()` though.

**Comment by soumyatheman** [comment]
> No fix that I know of. We could add `preinstall()` though.

The point is, will it reinstall that, which is deleted via removescript?

**Comment by Henryws** [comment]
Stale.
