### ISSUE TITLE
Installing Steam Tinker Launch with Pacstall in Ubuntu 22.10 Breaks the Software Updater Application

### ISSUE THREAD

**Issue by intelligentgaming** [pacstall/pacstall#788]
### Describe the bug

Good evening all.

After installing Steam Tinker Launch using Pacstall in Ubuntu 22.10 the Software Updater application now crashes with the below.

### To reproduce

To test this, I reverted back to an earlier Timeshift snapshot, and reinstalled Pacstall, rebooted, and ran Software Updater which worked correctly.

I then installed Steam Tinker Launch using Pacstall and Software Updater was broken again.

Luckily I can still update the system using sudo apt update && sudo apt upgrade -y but this is still an annoying bug.

Any ideas?

### Expected behavior

Software Updater should launch without error. 

### Screenshots

![218277166-b996e9f9-706c-4c4e-a8b0-547f23f39f2b](https://user-images.githubusercontent.com/67860954/218278104-3c78cd02-2456-439a-b40b-93a87844a7b4.png)

### OS version

Ubuntu 22.10

### Pacstall version

3.4.0 Hibiscus

**Comment by Henryws** [comment]
Yad hasn't been updated in a while, so I don't understand how it's breaking software updater.

**Comment by Henryws** [comment]
Stale.
