### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by rafay99-epic** [pacstall/pacstall#865]
# Question:
So here is my question.
Is there any parameter or flag that I can use to bypass this promote:
![image](https://user-images.githubusercontent.com/82662797/229173523-ad07f221-5a76-41ba-9c8f-b89d5e7efbed.png)

# Reason for Removing:
I try multiple distros that are based on Debian, or currently I am using Debian. I need a way to install applications simply and quickly, and I love pacman. because I have written a script that will check my OS and install and configure my system the way I like it.
By the way, great job, and I love this project; it's a real life saver and time saver.

So can you help?

**Comment by Henryws** [comment]
`-PI`

**Comment by rafay99-epic** [comment]
Thank you; I will try this and then let you know.
