### ISSUE TITLE
Upgrade won't work

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall#90]
**Describe the bug**
When upgrading, pacstall will look for /var/log/pacstall_installed/pkg, but with the new format, packages are logged at /var/log/pacstall/pkg

**To Reproduce**
Install pacstall, install something and upgrade

**Expected behavior**
For it to work

**Desktop (please complete the following information):**

- OS + version: Ubuntu 20.04
- Pacstall Version + branch: 1.5 develop

**Comment by wizard-28** [comment]
Yeah, so update the reader with the correct path.

**Comment by wizard-28** [comment]
And manually move the location of the logs to the new directory, or reinstall the programs

**Comment by Henryws** [comment]
> Yeah, so update the reader with the correct path.

Wdym reader?

**Comment by wizard-28** [comment]
I mean the code of `-Qi` script that "reads" the log files.

**Comment by Henryws** [comment]
> I mean the code of `-Qi` (and other) script that "reads" the log files.

Yeah, that's what I mean

**Comment by wizard-28** [comment]
Can you do this patch yourself, I will be MIA for the next month too. [These are the erroneous files](https://github.com/pacstall/pacstall/search?q=%2Fvar%2Flog%2Fpacstall_installed%2F)  which are to be patched.
