### ISSUE TITLE
Install packages without having to be root

### ISSUE THREAD

**Issue by LaVie024** [pacstall/pacstall#91]
To make it function more like the actual AUR, pacstall at the least, allow installation of packages and updates without having to be root. I'd like to add that makepkg deliberately prevents installing AUR packages as root, not only chroots into separate environment to make sure that nothing outside gets screwed.

If anything, I see this as a flaw and potential security issue. I get it may be hard to make this happen but pacstall could be better if it could happen.

**Comment by Henryws** [comment]
This was implemented in 1.4

**Comment by NarutoXY** [comment]
The issue was related to implementation of fakeroot. Like in Arch, package is build in a self contained environment. So it cannot mess with other things. When its done, the package is installed in the system with root privileges.
