### ISSUE TITLE
Domain https://pacstall.dev: Bad Request -502

### ISSUE THREAD

**Issue by 0n1cOn3** [pacstall/pacstall#910]
### Describe the bug

I was on the way to install pacstall but the domain does only reply with a Server error code 502

### To reproduce

sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install || wget -q https://pacstall.dev/q/install -O -)"
curl: (22) The requested URL returned error: 502 Bad Gateway

### Expected behavior

Went through the installer

### Screenshots

![grafik](https://github.com/pacstall/pacstall/assets/27576311/589ddcc2-e8fa-41e1-9da9-efaa013f465e)

### OS version

Raspbian 10 buster, ARMv7

### Pacstall version

master branch

**Comment by Henryws** [comment]
It should be up now.
