### ISSUE TITLE
Pacstall does not respect `http_proxy`/`https_proxy` env variables

### ISSUE THREAD

**Issue by Strongleong** [pacstall/pacstall#914]
### Describe the bug

I have Windows 10 PC in behind corporate proxy. I want to work with linux, so I installed Ubuntu with WSL2. I setup proxy connection. (`curl`, `apt`, `git` etc. works as intented). 

But when I try to install anything through `pacstall` it dies when it try to download package:

```console
strongleong@ubuntu:~$ pacstall -I neovim
(neovim) Do you want to view/edit the pacscript [y/N]
[+] INFO: Sourcing pacscript
[+] INFO: Retrieving packages
Initializing download: https://github.com/neovim/neovim/archive/refs/tags/v0.9.0.tar.gz
ERROR 400: Bad Request.
[!] ERROR: Failed to download package
[+] INFO: Cleaning up
```

### To reproduce

Just try to install anything behind proxy

### Expected behavior

The package gets installed as exptected

### Screenshots

![image](https://github.com/pacstall/pacstall/assets/17177071/8df85a31-8b2b-4b94-ac03-cffacf030ef8)

### OS version

Ubuntu 22.04 (WSL2)

### Pacstall version

3.13.0 Immortelle

**Comment by Henryws** [comment]
Could you try running `export PACSTALL_DOWNLOADER=curl` and try again?

**Comment by Strongleong** [comment]
This worked, thx.

Just found out that I should set my proxy setting for wget into `~/.wgetrc`. My bad 😅
