### ISSUE TITLE
Check if user uses doas or sudo

### ISSUE THREAD

**Issue by sil3abdi** [pacstall/pacstall#958]
## My Problem and How I Fixed it Manually

I've installed Debian 12 in a minimal way so I can choose the only packages I want to use, one of these packages was `doas` because you know **sudo is bloated**, I really don't like `sudo` that I removed the `sudo` group and created the `wheel` group instead so as not to have the word "*sudo*" in my computer XD.

When I installed `pacstall` I got the package `sudo` installed as well (I think that because it's a dependency) and it automatically created the sudo group in /etc/group. To solve that, I removed both `sudo` (the package itself) and the group, and then I did:
```bash
cd /usr/share/pacstall/scripts/
doas sed 's/sudo/doas/g' -i *
```
And then pacstall was working perfectly fine until I did `pacstall -U`, I had to reenter the same previous commands to get doas used instead of sudo.

### The Request 
So could you please guys fix that by adding a way to know if the user is using doas or sudo and use that information in the script and in dependencies list, I'd really appreciate that. 

Just and Idea how to do that in bash scipting
```bash
if which doas 2>/dev/null; then
    ## add this line to each scirpt: alias sudo=doas
fi
```

**Comment by oklopfer** [comment]
By default, both Ubuntu and Debian ship with sudo - and as you mentioned, you opted out of installing this package. This issue would only exist for those who specifically chose a custom install that did not include this central default package; therefore, we will not be fixing this issue. If you would like to use Pacstall correctly, make sure you install sudo. Thank you.

**Comment by Elsie19** [comment]
> "Most programs which prompt for root or admin access do not use sudo in the background, they use PAM. No program should ever call sudo directly." - A person on Reddit. Is that true for shell scripts like this?

The first part has some parts correct. Usually GUI programs don't call `sudo`, but call `pkexec` instead. That last sentence is problematic and untrue. For public shell scripts, 99% of people use `sudo`.
