### ISSUE TITLE
Not leaving empty lines at the end of a *.pacscript generates invalid *.postinst and *.postrm scripts

### ISSUE THREAD

**Issue by FelisDiligens** [pacstall/pacstall#965]
### Describe the bug

I'm currently working on a pacscript with `package`, `post_install`, and `post_remove` functions and noticed a small issue that can lead to completely broken deb packages.

Say we have a pacscript that ends like this:
```bash
# ...

post_remove() {
  echo "Hello, world"
}
```
(notice the missing newline at the end)

The resulting `/var/lib/dpkg/info/*.postinst` script will look like this:
```bash
#...

post_remove() {
  echo "Hello, world"
}post_install
```

And the resulting `/var/lib/dpkg/info/*.postrm` script similarliy will look like this:
```bash
#...

post_remove() {
  echo "Hello, world"
}post_remove
sudo rm -f /var/lib/pacstall/metadata/xone-git
sudo rm -f /etc/apt/preferences.d/xone-git-pin
```

Which fails with the following error message:
```txt
The following NEW packages will be installed:
  xone-git
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/109 kB of archives.
After this operation, 333 kB of additional disk space will be used.
Get:1 /usr/src/pacstall/xone-git.deb xone-git amd64 0.3-pacstall1~gitbbf0dcc4 [109 kB]
Selecting previously unselected package xone-git.
(Reading database ... 434275 files and directories currently installed.)
Preparing to unpack /usr/src/pacstall/xone-git.deb ...
Unpacking xone-git (0.3-pacstall1~gitbbf0dcc4) ...
Setting up xone-git (0.3-pacstall1~gitbbf0dcc4) ...
/var/lib/dpkg/info/xone-git.postinst: line 145: syntax error: unexpected end of file
dpkg: error processing package xone-git (--configure):
 installed xone-git package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 xone-git
	[!] ERROR: Failed to install xone-git deb
/var/lib/dpkg/info/xone-git.postrm: line 147: syntax error: unexpected end of file
dpkg: error processing package xone-git (--remove):
 installed xone-git package post-removal script subprocess returned error exit status 2
Errors were encountered while processing:
 xone-git
```

See the relevant messages:
```txt
/var/lib/dpkg/info/xone-git.postinst: line 145: syntax error: unexpected end of file
dpkg: error processing package xone-git (--configure):
 installed xone-git package post-installation script subprocess returned error exit status 2
```

and:
```txt
/var/lib/dpkg/info/xone-git.postrm: line 147: syntax error: unexpected end of file
dpkg: error processing package xone-git (--remove):
 installed xone-git package post-removal script subprocess returned error exit status 2
```

I had to edit the `*.postrm` manually in order to remove it with `sudo apt remove xone-git`

### To reproduce

Not leaving additional newlines at the end of a pacscript (that creates a *.deb file) after a `post_remove` or `post_install` function.

### Expected behavior

The resulting `*.postinst` and `*.postrm` scripts should have a additional newline for good measure:
```bash
post_remove() {
  echo "Hello, world"
}
post_remove
```

### Screenshots

n/a

### OS version

Ubuntu 23.04

### Pacstall version

4.0.1 Kokam, master branch (installed via the command on pacstall.dev)

**Comment by Elsie19** [comment]
Can you run `pacstall -U Elsie19:oopsies-v5` and try it again? If it works, run `pacstall -U pacstall:master` to go back.

**Comment by FelisDiligens** [comment]
> Can you run `pacstall -U Elsie19:oopsies-v5` and try it again?

This worked. 🚀

**Comment by Elsie19** [comment]
This will be released hopefully within the week. If you need the fix now, just edit `/usr/share/pacstall/scripts/install-local.sh` and make it look like this: https://github.com/pacstall/pacstall/blob/661bb2dd76f1b99c4c1f36aa12d8001001edd63b/misc/scripts/install-local.sh#L538

**Comment by FelisDiligens** [comment]
Ok, thanks!
