### ISSUE TITLE
Discord packages missing dependency on Rhino Linux (libgconf-2-4)

### ISSUE THREAD

**Issue by esa1975** [pacstall/pacstall#981]
### Describe the bug

When attempting to install either discord or discord-deb on Rhino Linux, I receive the following error:

The following packages have unmet dependencies:
 discord : Depends: libgconf-2-4 but it is not installable
[!] ERROR: Failed to install the package

### To reproduce

On Rhino Linux 2023.2, attempt to install either discord or discord-deb via 'rhino-pkg install discord' or 'pacstall -I discord' (or alternately discord-deb).

### Expected behavior

The libgconf-2-4 is available for the discord packages to be installed properly.

### Screenshots

![Screenshot_2023-09-11_21-24-17](https://github.com/pacstall/pacstall/assets/50505461/6a6f9cb4-5e39-4db0-bb70-0e8d2c101a0d)

### OS version

Rhino Linux 2023.2

### Pacstall version

4.1.1 Amethyst

**Comment by Elsie19** [comment]
I successfully installed and ran discord even when I removed the `libgconf-2-4` dependency from the array.

**Comment by Elsie19** [comment]
Closed with https://github.com/pacstall/pacstall-programs/commit/dab1e9faabc117f41505419ee07531c529dd0d9f
