### ISSUE TITLE
Implement `pacstall-qa` for Testing Merge Requests Locally

### ISSUE THREAD

**Issue by oklopfer** [pacstall/pacstall#984]
### Is your feature related to a problem? Please describe.

Currently, there's no straightforward way to locally test a merge request for a package before it is merged. Sometimes, the CI does not give us enough information to confirm a package works, and our only way to check is to clone the files separately and install them local.

### A clear and concise description of what you want to happen.

I propose the creation of a new script, `pacstall-qa`, which would mimic the functionality of `ubports-qa`. it should be possible to test it locally on the user's system using a command like:
 ```bash
 pacstall-qa PR_pacstall-programs_984 -I linux-image-okpine-deb
 ```

### Describe alternatives you've considered

The current alternative approach is to manually clone the merge request branch locally and perform the installation. Which sucks.

### Additional context

When a merge request is pushed for an Ubuntu Touch package, it is added to a repo styled `focal_-_PR_${appname}-${MR#}`, and one can install it locally on their device by running `ubports-qa install focal_-_PR_${appname}-${MR#}` to test out that merge for *quality assurance*.

**Comment by Elsie19** [comment]
Maybe we could do:

```bash
pacstall-qa github:pacstall/pacstall-programs/984 -I linux-image-okpine-deb
```

As a cleaner and more extensible way.

**Comment by Elsie19** [comment]
```nu
#!/usr/bin/env nu

def parse-pr [pr: string] -> list {
    return ($pr | parse "{provider}:{user}/{repo}/{pr}")
}

def parse-link [provider: list, pkg: string] -> [list<string, list>] {
    match $provider.provider.0 {
        "github" => {
            let gh_provides = (http get $"https://api.github.com/repos/pacstall/pacstall-programs/pulls/($provider.pr.0)")
            return [$"https://raw.githubusercontent.com/($gh_provides.head.repo.full_name)/($gh_provides.head.ref)/packages/($pkg)/($pkg).pacscript" $gh_provides]
            },
        _ => {
                print -e $"($provider.provider.0) is not a valid provider!"
                exit 1
             },
    }
}

# A tool to target and install packages based off of PRs
def main [
         --metalink (-m): string # Parse a URL to target for pacstall
         --install (-I): string # Package to install
         ] -> int {

    if ($metalink | is-empty) or ($install | is-empty) {
        print -e "'--metalink' and '--install' cannot be empty!"
        exit 1
    }
    let parsed_pr = (parse-pr $metalink)
    let provider_url = (parse-link $parsed_pr $install)
    $provider_url
    ^wget -q $provider_url.0 -O $"($install).pacscript"
    print $"Installing (ansi green)($install)(ansi reset)\((ansi purple)($provider_url.1.user.login)(ansi reset):(ansi red)($parsed_pr.pr.0)(ansi reset)\)"
    ^pacstall -I $"($install).pacscript"
    rm -f $"($install).pacscript"
}
```

**Comment by Elsie19** [comment]
https://github.com/pacstall/pacstall-qa
