### ISSUE TITLE
rhino-pkg wants to uninstall timeshift

### ISSUE THREAD

**Issue by servimo** [pacstall/pacstall#987]
### Describe the bug

rhino-pkg wants to uninstall timeshift. How to not do this? I want to update my system, but keep timeshift. Didn´t found any command to do this. Maybe I didn´t search much. 

### To reproduce

just run rhino-pkg update

### Expected behavior

not want to uninstall timeshift

### Screenshots

![Captura de tela_2023-10-11_10-38-14](https://github.com/pacstall/pacstall/assets/10197145/4956e0eb-c11a-46a7-a56c-bda5c18b82f5)

### OS version

Rhino Rolling Release

### Pacstall version

4.1.1 Amethyst

**Comment by Elsie19** [comment]
It's a required package in Rhino. Also this should be in pacstall-programs, not pacstall.

**Comment by oklopfer** [comment]
It was removed from being a core dependency in favor of just being pre-installed on future ISOs. When you updated rhino-core, it set timeshift to "automatically installed, not required." To fix it, you should just have to run either `sudo apt install timeshift` or `pacstall -PI timeshift` to set it to "manually installed" so it is required.

**Comment by servimo** [comment]
"pacstall -PI timeshift" fixed it.
