### ISSUE TITLE
pacdep: Could not enter into the downloaded archive

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacstall#991]
### Describe the bug

In https://github.com/pacstall/pacstall-programs/pull/4651, I have nerd-fonts-hack as a pacdep.
It fails to install as a pacdep with 
```
Downloaded 10.7797 Megabyte(s) in 13 second(s). (819.66 KB/s)
[+] INFO: Extracting Hack.zip
[*] WARNING: Could not enter into the downloaded archive
```

### To reproduce

`pacstall-qa -m github:pacstall/pacstall-programs/4651 -I oh-my-posh-git`

### Expected behavior

Install `nerd-fonts-hack` as pacdep succeeds
The pacscript seems to not be faulty since it installs fine with `pacstall -I nerd-fonts-hack`

### Screenshots

![image](https://github.com/pacstall/pacstall/assets/10415894/54ccbcea-03f0-4281-8dbc-f5b3492a2693)

### OS version

Tuxedo OS 2

### Pacstall version

4.2.0

EDIT: edited the reproduce command

**Comment by Elsie19** [comment]
You're using pacstall-qa, test it with pacstall proper.

**Comment by Zahrun** [comment]
Same thing happens

**Comment by Elsie19** [comment]
Does it happen in 4.1.1?

**Comment by Zahrun** [comment]
> Does it happen in 4.1.1?

Yes. Even the CI failed like that https://github.com/pacstall/pacstall-programs/pull/4651

**Comment by Elsie19** [comment]
What's the last version you know this worked on?

**Comment by oklopfer** [comment]
The metalink is wrong shouldn't it be pacstall/pacstall-programs

**Comment by Zahrun** [comment]
That is there also in the pacstall-qa repo https://github.com/pacstall/pacstall-qa/blob/master/README.md?plain=1#L18

But anyway the pacscript gets downloaded fine, the issue is not about pacstall-qa

**Comment by Elsie19** [comment]
Yeah that's my bad, I'll fix it soon.

**Comment by oklopfer** [comment]
This looks to be an issue with nerds-font-hack package, not with pacstall

**Comment by Zahrun** [comment]
The pacscript seems to not be faulty since it installs fine with pacstall -I nerd-fonts-hack

**Comment by oklopfer** [comment]
Yep sorry I see that now. I'll take a look

**Comment by oklopfer** [comment]
@Zahrun it should work now. was a problem with the package after all. https://github.com/pacstall/pacstall-programs/commit/78714cecb448edbf323e8d10d64d408eebbf01c6

**Comment by Zahrun** [comment]
Thank you 🙏
