### ISSUE TITLE
Remove all installed packages

### ISSUE THREAD

**Issue by 8ullyMaguire** [pacstall/pacstall#999]
### Is your feature related to a problem? Please describe.

Have to remove packages one by one.

### A clear and concise description of what you want to happen.

Would be nice to be able to remove all packages at once.

### Describe alternatives you've considered

```bash
#!/bin/bash

# Get list of all pacstall packages
pacstall_packages=$(pacstall -L | awk '{print $1}' | sed 's/@.*//') 

# Loop through list and remove each package
for package in $pacstall_packages; do
  echo "Removing $package"
  pacstall -R "$package"
done
```

**Comment by Elsie19** [comment]
Do you want to uninstall entirely?
